-- JSON to Database Sync - Generated Schema
-- Generated: 2025-07-07T22:07:30.375864
-- Source: data\raw_json\json_compiled

-- Enable foreign key constraints
PRAGMA foreign_keys = ON;

-- Main Entity Tables
--------------------------------------------------
-- Table: json_bills
CREATE TABLE IF NOT EXISTS json_bills (
    bill_id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    vendor_id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    vendor_name VARCHAR(255) NOT NULL,
    status VARCHAR(100) NOT NULL,
    color_code TEXT,
    current_sub_status_id INTEGER PRIMARY KEY AUTOINCREMENT,
    current_sub_status VARCHAR(100) NOT NULL,
    bill_number VARCHAR(50),
    reference_number TEXT,
    date DATETIME NOT NULL,
    due_date DATETIME NOT NULL,
    due_days VARCHAR(50),
    currency_id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    currency_code VARCHAR(50) NOT NULL,
    price_precision DECIMAL(15,2) NOT NULL,
    exchange_rate REAL NOT NULL,
    total DECIMAL(15,2) NOT NULL,
    tds_total DECIMAL(15,2) NOT NULL,
    balance DECIMAL(15,2) NOT NULL,
    unprocessed_payment_amount DECIMAL(15,2) NOT NULL,
    created_time DATETIME NOT NULL,
    last_modified_time DATETIME NOT NULL,
    is_opening_balance DECIMAL(15,2) NOT NULL,
    attachment_name TEXT,
    has_attachment INTEGER NOT NULL,
    tags VARCHAR(50) NOT NULL,
    is_uber_bill INTEGER NOT NULL,
    is_tally_bill INTEGER NOT NULL,
    cf_chp_scheme_settlement_perio VARCHAR(50) NOT NULL,
    cf_chp_scheme_settlement_perio_unformatted VARCHAR(50) NOT NULL,
    entity_type VARCHAR(100) NOT NULL,
    client_viewed_time DATETIME,
    is_viewed_by_client INTEGER NOT NULL,
    branch_id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    branch_name VARCHAR(255) NOT NULL,
    location_id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    is_bill_reconciliation_violated INTEGER NOT NULL,
    PRIMARY KEY (bill_id, vendor_id, current_sub_status_id, currency_id, branch_id, location_id)
);

-- Table: json_contacts
CREATE TABLE IF NOT EXISTS json_contacts (
    contact_id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    contact_name VARCHAR(255) NOT NULL,
    customer_name VARCHAR(255) NOT NULL,
    vendor_name VARCHAR(255) NOT NULL,
    company_name VARCHAR(255),
    website VARCHAR(255),
    language_code VARCHAR(50),
    language_code_formatted VARCHAR(50),
    contact_type VARCHAR(100) NOT NULL,
    contact_type_formatted VARCHAR(100) NOT NULL,
    status VARCHAR(100) NOT NULL,
    customer_sub_type VARCHAR(100) NOT NULL,
    source VARCHAR(50),
    is_linked_with_zohocrm INTEGER NOT NULL,
    payment_terms INTEGER NOT NULL,
    payment_terms_label VARCHAR(50) NOT NULL,
    currency_id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    twitter TEXT,
    facebook TEXT,
    currency_code VARCHAR(50) NOT NULL,
    outstanding_receivable_amount DECIMAL(15,2) NOT NULL,
    outstanding_receivable_amount_bcy DECIMAL(15,2) NOT NULL,
    outstanding_payable_amount DECIMAL(15,2) NOT NULL,
    outstanding_payable_amount_bcy DECIMAL(15,2) NOT NULL,
    unused_credits_receivable_amount DECIMAL(15,2) NOT NULL,
    unused_credits_receivable_amount_bcy DECIMAL(15,2) NOT NULL,
    unused_credits_payable_amount DECIMAL(15,2) NOT NULL,
    unused_credits_payable_amount_bcy DECIMAL(15,2) NOT NULL,
    customer_credit_limit TEXT,
    first_name TEXT,
    last_name TEXT,
    email VARCHAR(255),
    phone VARCHAR(255),
    mobile VARCHAR(50),
    portal_status VARCHAR(100) NOT NULL,
    portal_status_formatted VARCHAR(100) NOT NULL,
    created_time DATETIME NOT NULL,
    created_time_formatted DATETIME NOT NULL,
    last_modified_time DATETIME NOT NULL,
    last_modified_time_formatted DATETIME NOT NULL,
    custom_fields TEXT NOT NULL,
    cf_market_region VARCHAR(50) NOT NULL,
    cf_market_region_unformatted VARCHAR(50) NOT NULL,
    cf_customer_category VARCHAR(100) NOT NULL,
    cf_customer_category_unformatted VARCHAR(100) NOT NULL,
    cf_customer_owner VARCHAR(50) NOT NULL,
    cf_customer_owner_unformatted VARCHAR(50) NOT NULL,
    custom_field_hash VARCHAR(255) NOT NULL,
    tags VARCHAR(50) NOT NULL,
    ach_supported INTEGER NOT NULL,
    has_attachment INTEGER NOT NULL,
    cf_special_scheme_targets VARCHAR(50),
    cf_special_scheme_targets_unformatted VARCHAR(50),
    PRIMARY KEY (contact_id, currency_id)
);

-- Table: json_credit_notes
CREATE TABLE IF NOT EXISTS json_credit_notes (
    creditnote_id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    creditnote_number VARCHAR(50) NOT NULL,
    status VARCHAR(100) NOT NULL,
    reference_number VARCHAR(50) NOT NULL,
    date DATETIME NOT NULL,
    total DECIMAL(15,2) NOT NULL,
    balance DECIMAL(15,2) NOT NULL,
    branch_id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    branch_name VARCHAR(255) NOT NULL,
    location_id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    customer_id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    customer_name VARCHAR(255) NOT NULL,
    applied_invoices TEXT,
    is_emailed VARCHAR(255) NOT NULL,
    has_attachment INTEGER NOT NULL,
    cf_region VARCHAR(50) NOT NULL,
    cf_region_unformatted VARCHAR(50) NOT NULL,
    cf_scheme_type VARCHAR(100) NOT NULL,
    cf_scheme_type_unformatted VARCHAR(100) NOT NULL,
    cf_scheme_settlement_period VARCHAR(50) NOT NULL,
    cf_scheme_settlement_period_unformatted VARCHAR(50) NOT NULL,
    cf_modified DATETIME NOT NULL,
    cf_modified_unformatted DATETIME NOT NULL,
    cf_dispatch_incomplete_but_sch VARCHAR(50) NOT NULL,
    cf_dispatch_incomplete_but_sch_unformatted VARCHAR(50) NOT NULL,
    salesperson_name VARCHAR(255) NOT NULL,
    salesperson_id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    is_viewed_by_client INTEGER NOT NULL,
    client_viewed_time DATETIME,
    color_code TEXT,
    current_sub_status_id INTEGER PRIMARY KEY AUTOINCREMENT,
    current_sub_status VARCHAR(100) NOT NULL,
    currency_id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    currency_code VARCHAR(50) NOT NULL,
    created_time DATETIME NOT NULL,
    last_modified_time DATETIME NOT NULL,
    exchange_rate REAL NOT NULL,
    template_id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    template_type VARCHAR(100) NOT NULL,
    rounding_mode VARCHAR(50) NOT NULL,
    price_precision DECIMAL(15,2) NOT NULL,
    tags VARCHAR(50) NOT NULL,
    PRIMARY KEY (creditnote_id, branch_id, location_id, customer_id, salesperson_id, current_sub_status_id, currency_id, template_id)
);

-- Table: json_customer_payments
CREATE TABLE IF NOT EXISTS json_customer_payments (
    payment_id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    payment_number VARCHAR(50) NOT NULL,
    retainerinvoice_id INTEGER PRIMARY KEY AUTOINCREMENT,
    invoice_numbers TEXT,
    date DATETIME NOT NULL,
    payment_mode VARCHAR(50) NOT NULL,
    payment_mode_formatted VARCHAR(50) NOT NULL,
    amount DECIMAL(15,2) NOT NULL,
    bcy_amount DECIMAL(15,2) NOT NULL,
    unused_amount DECIMAL(15,2) NOT NULL,
    bcy_unused_amount DECIMAL(15,2) NOT NULL,
    account_id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    account_name VARCHAR(255) NOT NULL,
    description TEXT,
    reference_number TEXT,
    branch_id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    branch_name VARCHAR(255) NOT NULL,
    location_id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    customer_id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    customer_name VARCHAR(255) NOT NULL,
    created_time DATETIME NOT NULL,
    last_modified_time DATETIME NOT NULL,
    last_four_digits TEXT,
    gateway_transaction_id INTEGER PRIMARY KEY AUTOINCREMENT,
    payment_gateway TEXT,
    bcy_refunded_amount DECIMAL(15,2) NOT NULL,
    applied_invoices VARCHAR(50) NOT NULL,
    has_attachment INTEGER NOT NULL,
    tags VARCHAR(50) NOT NULL,
    documents TEXT,
    custom_fields_list TEXT,
    tax_account_id INTEGER PRIMARY KEY AUTOINCREMENT,
    tax_account_name TEXT,
    tax_amount_withheld DECIMAL(15,2) NOT NULL,
    payment_type VARCHAR(100) NOT NULL,
    payment_status VARCHAR(100) NOT NULL,
    settlement_status VARCHAR(100),
    PRIMARY KEY (payment_id, retainerinvoice_id, account_id, branch_id, location_id, customer_id, gateway_transaction_id, tax_account_id)
);

-- Table: json_invoices
CREATE TABLE IF NOT EXISTS json_invoices (
    ach_payment_initiated INTEGER NOT NULL,
    invoice_id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    zcrm_potential_id INTEGER PRIMARY KEY AUTOINCREMENT,
    customer_id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    location_id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    branch_id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    zcrm_potential_name TEXT,
    customer_name VARCHAR(255) NOT NULL,
    company_name VARCHAR(255),
    status VARCHAR(100) NOT NULL,
    invoice_number VARCHAR(50) NOT NULL,
    reference_number VARCHAR(50),
    date DATETIME NOT NULL,
    due_date DATETIME NOT NULL,
    due_days VARCHAR(50),
    email VARCHAR(255),
    project_name TEXT,
    branch_name VARCHAR(255) NOT NULL,
    billing_address VARCHAR(255) NOT NULL,
    shipping_address VARCHAR(255) NOT NULL,
    country VARCHAR(50),
    phone VARCHAR(255),
    created_by DATETIME NOT NULL,
    total DECIMAL(15,2) NOT NULL,
    balance DECIMAL(15,2) NOT NULL,
    payment_expected_date DATETIME,
    custom_fields VARCHAR(50) NOT NULL,
    custom_field_hash VARCHAR(50) NOT NULL,
    tags VARCHAR(50) NOT NULL,
    salesperson_name VARCHAR(255) NOT NULL,
    shipping_charge REAL NOT NULL,
    adjustment REAL NOT NULL,
    created_time DATETIME NOT NULL,
    last_modified_time DATETIME NOT NULL,
    updated_time DATETIME NOT NULL,
    is_viewed_by_client INTEGER NOT NULL,
    has_attachment INTEGER NOT NULL,
    client_viewed_time DATETIME,
    is_emailed VARCHAR(255) NOT NULL,
    color_code TEXT,
    current_sub_status_id INTEGER PRIMARY KEY AUTOINCREMENT,
    current_sub_status VARCHAR(100) NOT NULL,
    currency_id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    schedule_time DATETIME,
    currency_code VARCHAR(50) NOT NULL,
    currency_symbol VARCHAR(50) NOT NULL,
    template_type VARCHAR(100) NOT NULL,
    no_of_copies INTEGER NOT NULL,
    show_no_of_copies INTEGER NOT NULL,
    invoice_url VARCHAR(255) NOT NULL,
    transaction_type VARCHAR(100) NOT NULL,
    reminders_sent INTEGER NOT NULL,
    last_reminder_sent_date DATETIME,
    last_payment_date DATETIME,
    template_id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    documents TEXT,
    salesperson_id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    write_off_amount DECIMAL(15,2) NOT NULL,
    exchange_rate REAL NOT NULL,
    unprocessed_payment_amount DECIMAL(15,2) NOT NULL,
    PRIMARY KEY (invoice_id, zcrm_potential_id, customer_id, location_id, branch_id, current_sub_status_id, currency_id, template_id, salesperson_id)
);

-- Table: json_items
CREATE TABLE IF NOT EXISTS json_items (
    item_id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    name VARCHAR(255) NOT NULL,
    item_name VARCHAR(255) NOT NULL,
    unit TEXT,
    status VARCHAR(100) NOT NULL,
    source VARCHAR(50) NOT NULL,
    is_linked_with_zohocrm INTEGER NOT NULL,
    zcrm_product_id INTEGER PRIMARY KEY AUTOINCREMENT,
    description TEXT,
    rate REAL NOT NULL,
    tax_id INTEGER PRIMARY KEY AUTOINCREMENT,
    tax_name TEXT,
    tax_percentage INTEGER NOT NULL,
    purchase_account_id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    purchase_account_name VARCHAR(255) NOT NULL,
    account_id INTEGER PRIMARY KEY AUTOINCREMENT,
    account_name VARCHAR(255),
    purchase_description TEXT,
    purchase_rate REAL NOT NULL,
    can_be_sold INTEGER NOT NULL,
    can_be_purchased INTEGER NOT NULL,
    track_inventory INTEGER NOT NULL,
    item_type VARCHAR(100) NOT NULL,
    product_type VARCHAR(100) NOT NULL,
    stock_on_hand REAL NOT NULL,
    has_attachment INTEGER NOT NULL,
    available_stock REAL NOT NULL,
    actual_available_stock REAL NOT NULL,
    sku VARCHAR(50),
    reorder_level REAL,
    image_name TEXT,
    image_type VARCHAR(100),
    image_document_id INTEGER PRIMARY KEY AUTOINCREMENT,
    created_time DATETIME NOT NULL,
    last_modified_time DATETIME NOT NULL,
    cf_sku_category VARCHAR(100) NOT NULL,
    cf_sku_category_unformatted VARCHAR(100) NOT NULL,
    cf_item_location VARCHAR(50) NOT NULL,
    cf_item_location_unformatted VARCHAR(50) NOT NULL,
    cf_product_category VARCHAR(100) NOT NULL,
    cf_product_category_unformatted VARCHAR(100) NOT NULL,
    cf_manufacturer VARCHAR(50) NOT NULL,
    cf_manufacturer_unformatted VARCHAR(50) NOT NULL,
    tags VARCHAR(50) NOT NULL,
    cf_product_sale_category VARCHAR(100),
    cf_product_sale_category_unformatted VARCHAR(100),
    PRIMARY KEY (item_id, zcrm_product_id, tax_id, purchase_account_id, account_id, image_document_id)
);

-- Table: json_organizations
CREATE TABLE IF NOT EXISTS json_organizations (
    isorgnotsupported INTEGER NOT NULL,
    organization_id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    name VARCHAR(255) NOT NULL,
    contact_name VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL,
    source INTEGER NOT NULL,
    country VARCHAR(50) NOT NULL,
    country_code VARCHAR(50) NOT NULL,
    org_settings INTEGER NOT NULL,
    is_ziedition INTEGER NOT NULL,
    custom_field_type VARCHAR(100) NOT NULL,
    custom_fields VARCHAR(255) NOT NULL,
    is_sku_enabled INTEGER NOT NULL,
    phone VARCHAR(255),
    org_type VARCHAR(100) NOT NULL,
    state_code VARCHAR(100),
    state VARCHAR(100),
    zoho_one_org TEXT,
    zi_zb_edition INTEGER NOT NULL,
    org_created_app_source DATETIME NOT NULL,
    zi_zb_client INTEGER NOT NULL,
    is_solo_org INTEGER NOT NULL,
    partners_domain TEXT,
    version VARCHAR(50) NOT NULL,
    version_formatted VARCHAR(50) NOT NULL,
    is_search360_enabled INTEGER NOT NULL,
    is_sales_inclusive_tax_enabled INTEGER NOT NULL,
    sales_tax_type VARCHAR(100) NOT NULL,
    tax_group_enabled INTEGER NOT NULL,
    language_code VARCHAR(50) NOT NULL,
    fiscal_year_start_month INTEGER NOT NULL,
    time_zone DATETIME NOT NULL,
    field_separator TEXT,
    time_zone_formatted DATETIME NOT NULL,
    can_change_timezone DATETIME NOT NULL,
    digital_signature_mode VARCHAR(50) NOT NULL,
    is_dsign_required INTEGER NOT NULL,
    can_sign_invoice INTEGER NOT NULL,
    is_user_dsign_mandatory INTEGER NOT NULL,
    currency_id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    currency_code VARCHAR(50) NOT NULL,
    currency_symbol VARCHAR(50) NOT NULL,
    currency_format VARCHAR(50) NOT NULL,
    price_precision DECIMAL(15,2) NOT NULL,
    org_joined_app_list VARCHAR(50) NOT NULL,
    other_active_services INTEGER NOT NULL,
    is_last_active_service INTEGER NOT NULL,
    is_designated_zone INTEGER NOT NULL,
    is_free_zone INTEGER NOT NULL,
    brexit_date DATETIME NOT NULL,
    is_brexit_applicable INTEGER NOT NULL,
    is_registered_for_tax INTEGER NOT NULL,
    is_moss_enabled INTEGER NOT NULL,
    is_tax_registered INTEGER NOT NULL,
    is_international_trade_enabled INTEGER NOT NULL,
    is_gst_india_version INTEGER NOT NULL,
    is_registered_for_gst INTEGER NOT NULL,
    isorgactive INTEGER NOT NULL,
    plan_type VARCHAR(100) NOT NULL,
    plan_name VARCHAR(255) NOT NULL,
    plan_period TEXT,
    account_created_date DATETIME NOT NULL,
    account_created_date_formatted DATETIME NOT NULL,
    is_org_active INTEGER NOT NULL,
    is_quick_setup_completed INTEGER NOT NULL,
    is_trial_period_extended INTEGER NOT NULL,
    is_trial_expired INTEGER NOT NULL,
    is_invoice_pmt_tds_allowed INTEGER NOT NULL,
    is_hsn_or_sac_enabled INTEGER NOT NULL,
    mode VARCHAR(50) NOT NULL,
    is_po_enabled INTEGER NOT NULL,
    is_salesorder_enabled INTEGER NOT NULL,
    is_inventory_enabled INTEGER NOT NULL,
    is_trial_extended INTEGER NOT NULL,
    zi_migration_status VARCHAR(100) NOT NULL,
    is_new_customer_custom_fields INTEGER NOT NULL,
    is_portal_enabled INTEGER NOT NULL,
    portal_name VARCHAR(255) NOT NULL,
    is_retainerinvoice_enabled INTEGER NOT NULL,
    is_bill_of_supply_enabled INTEGER NOT NULL,
    can_show_document_tab INTEGER NOT NULL,
    is_scan_preference_enabled INTEGER NOT NULL,
    is_user_accountant INTEGER NOT NULL,
    is_user_last_admin INTEGER NOT NULL,
    is_user_super_admin INTEGER NOT NULL,
    user_status VARCHAR(100) NOT NULL,
    user_status_formatted VARCHAR(100) NOT NULL,
    org_action VARCHAR(50) NOT NULL,
    applist VARCHAR(50) NOT NULL,
    is_zpayroll_grid INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    is_default_org INTEGER NOT NULL,
    is_subscription_paused INTEGER NOT NULL
);

-- Table: json_purchase_orders
CREATE TABLE IF NOT EXISTS json_purchase_orders (
    purchaseorder_id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    vendor_id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    vendor_name VARCHAR(255) NOT NULL,
    company_name VARCHAR(255) NOT NULL,
    order_status VARCHAR(100) NOT NULL,
    billed_status VARCHAR(100),
    received_status VARCHAR(100),
    status VARCHAR(100) NOT NULL,
    color_code TEXT,
    current_sub_status_id INTEGER PRIMARY KEY AUTOINCREMENT,
    current_sub_status VARCHAR(100) NOT NULL,
    purchaseorder_number VARCHAR(50) NOT NULL,
    reference_number TEXT,
    date DATETIME NOT NULL,
    delivery_date DATETIME,
    expected_delivery_date DATETIME,
    delivery_days TEXT,
    due_by_days TEXT,
    due_in_days TEXT,
    currency_id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    currency_code VARCHAR(50) NOT NULL,
    price_precision DECIMAL(15,2),
    total DECIMAL(15,2) NOT NULL,
    has_attachment INTEGER NOT NULL,
    tags VARCHAR(50) NOT NULL,
    created_time DATETIME NOT NULL,
    last_modified_time DATETIME NOT NULL,
    quantity_yet_to_receive REAL NOT NULL,
    quantity_marked_as_received INTEGER NOT NULL,
    is_po_marked_as_received INTEGER NOT NULL,
    receives VARCHAR(50) NOT NULL,
    client_viewed_time DATETIME,
    is_viewed_by_client INTEGER NOT NULL,
    branch_id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    branch_name VARCHAR(255) NOT NULL,
    location_id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    location_name VARCHAR(255),
    documents VARCHAR(50),
    contact_category VARCHAR(100),
    sub_statuses VARCHAR(100),
    contact_persons VARCHAR(50),
    contact_persons_associated VARCHAR(50),
    currency_symbol VARCHAR(50),
    exchange_rate REAL,
    is_emailed VARCHAR(255),
    is_inclusive_tax INTEGER,
    tax_rounding VARCHAR(50),
    is_adv_tracking_in_receive INTEGER,
    total_quantity DECIMAL(15,2),
    tds_calculation_type VARCHAR(100),
    line_items TEXT,
    has_qty_cancelled INTEGER,
    adjustment REAL,
    adjustment_description VARCHAR(255),
    discount_amount DECIMAL(15,2),
    discount REAL,
    discount_applied_on_amount DECIMAL(15,2),
    is_discount_before_tax INTEGER,
    discount_account_id INTEGER PRIMARY KEY AUTOINCREMENT,
    discount_account_name TEXT,
    discount_type VARCHAR(100),
    sub_total DECIMAL(15,2),
    sub_total_inclusive_of_tax DECIMAL(15,2),
    tax_total DECIMAL(15,2),
    discount_total DECIMAL(15,2),
    discount_percent REAL,
    taxes VARCHAR(50),
    computation_type VARCHAR(100),
    tax_override_preference VARCHAR(50),
    tds_override_preference VARCHAR(50),
    tds_summary VARCHAR(50),
    submitted_date DATETIME,
    submitted_by TEXT,
    submitted_by_name TEXT,
    submitted_by_email VARCHAR(255),
    submitted_by_photo_url VARCHAR(255),
    submitter_id INTEGER PRIMARY KEY AUTOINCREMENT,
    approver_id INTEGER PRIMARY KEY AUTOINCREMENT,
    approvers_list VARCHAR(50),
    billing_address_id INTEGER PRIMARY KEY AUTOINCREMENT,
    billing_address VARCHAR(255),
    notes TEXT,
    terms TEXT,
    payment_terms INTEGER,
    payment_terms_label VARCHAR(50),
    ship_via TEXT,
    ship_via_id INTEGER PRIMARY KEY AUTOINCREMENT,
    attention TEXT,
    delivery_org_address_id INTEGER PRIMARY KEY AUTOINCREMENT,
    delivery_customer_id INTEGER PRIMARY KEY AUTOINCREMENT,
    delivery_customer_address_id INTEGER PRIMARY KEY AUTOINCREMENT,
    delivery_address VARCHAR(1000),
    custom_fields VARCHAR(50),
    custom_field_hash VARCHAR(50),
    attachment_name TEXT,
    can_send_in_mail INTEGER,
    template_id INTEGER PRIMARY KEY AUTOINCREMENT,
    template_name VARCHAR(255),
    page_width VARCHAR(50),
    page_height VARCHAR(50),
    orientation VARCHAR(50),
    template_type VARCHAR(100),
    created_by_id INTEGER PRIMARY KEY AUTOINCREMENT,
    can_mark_as_bill INTEGER,
    can_mark_as_unbill INTEGER,
    salesorders VARCHAR(50),
    bills VARCHAR(50),
    advances VARCHAR(50),
    PRIMARY KEY (purchaseorder_id, vendor_id, current_sub_status_id, currency_id, branch_id, location_id, discount_account_id, submitter_id, approver_id, billing_address_id, ship_via_id, delivery_org_address_id, delivery_customer_id, delivery_customer_address_id, template_id, created_by_id)
);

-- Table: json_sales_orders
CREATE TABLE IF NOT EXISTS json_sales_orders (
    salesorder_id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    zcrm_potential_id INTEGER PRIMARY KEY AUTOINCREMENT,
    zcrm_potential_name TEXT,
    customer_name VARCHAR(255) NOT NULL,
    customer_id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    email VARCHAR(255),
    delivery_date DATETIME,
    company_name VARCHAR(255),
    color_code TEXT,
    current_sub_status_id INTEGER PRIMARY KEY AUTOINCREMENT,
    current_sub_status VARCHAR(100) NOT NULL,
    order_sub_status_id INTEGER PRIMARY KEY AUTOINCREMENT,
    pickup_location_id INTEGER PRIMARY KEY AUTOINCREMENT,
    invoiced_sub_status_id INTEGER PRIMARY KEY AUTOINCREMENT,
    order_sub_status VARCHAR(100),
    invoiced_sub_status VARCHAR(100),
    salesorder_number VARCHAR(50) NOT NULL,
    reference_number TEXT,
    date DATETIME NOT NULL,
    shipment_date DATETIME,
    shipment_days TEXT,
    due_by_days TEXT,
    due_in_days TEXT,
    currency_id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    source VARCHAR(50) NOT NULL,
    currency_code VARCHAR(50) NOT NULL,
    total DECIMAL(15,2) NOT NULL,
    bcy_total DECIMAL(15,2) NOT NULL,
    total_invoiced_amount DECIMAL(15,2) NOT NULL,
    created_time DATETIME NOT NULL,
    last_modified_time DATETIME NOT NULL,
    is_emailed VARCHAR(255) NOT NULL,
    quantity_invoiced REAL NOT NULL,
    order_status VARCHAR(100) NOT NULL,
    invoiced_status VARCHAR(100),
    paid_status VARCHAR(100),
    shipped_status VARCHAR(100),
    status VARCHAR(100) NOT NULL,
    order_fulfillment_type VARCHAR(100),
    is_manually_fulfilled INTEGER NOT NULL,
    salesperson_name VARCHAR(255),
    branch_id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    branch_name VARCHAR(255) NOT NULL,
    location_id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    has_attachment INTEGER NOT NULL,
    tags VARCHAR(50) NOT NULL,
    cf_region VARCHAR(50) NOT NULL,
    cf_region_unformatted VARCHAR(50) NOT NULL,
    custom_fields_list TEXT,
    delivery_method TEXT,
    delivery_method_id INTEGER PRIMARY KEY AUTOINCREMENT,
    is_viewed_in_mail INTEGER NOT NULL,
    mail_first_viewed_time DATETIME,
    mail_last_viewed_time DATETIME,
    is_scheduled_for_quick_shipment_create INTEGER NOT NULL,
    PRIMARY KEY (salesorder_id, zcrm_potential_id, customer_id, current_sub_status_id, order_sub_status_id, pickup_location_id, invoiced_sub_status_id, currency_id, branch_id, location_id, delivery_method_id)
);

-- Table: json_vendor_payments
CREATE TABLE IF NOT EXISTS json_vendor_payments (
    payment_id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    vendor_id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    currency_id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    status VARCHAR(100) NOT NULL,
    vendor_name VARCHAR(255) NOT NULL,
    bill_numbers TEXT,
    payment_mode VARCHAR(50) NOT NULL,
    payment_number VARCHAR(50) NOT NULL,
    description TEXT,
    date DATETIME NOT NULL,
    reference_number VARCHAR(50),
    exchange_rate REAL NOT NULL,
    amount DECIMAL(15,2) NOT NULL,
    bcy_amount DECIMAL(15,2) NOT NULL,
    paid_through_account_id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    paid_through_account_name VARCHAR(255) NOT NULL,
    balance DECIMAL(15,2) NOT NULL,
    currency_code VARCHAR(50) NOT NULL,
    bcy_balance DECIMAL(15,2) NOT NULL,
    created_time DATETIME NOT NULL,
    last_modified_time DATETIME NOT NULL,
    is_paid_via_print_check INTEGER NOT NULL,
    has_attachment INTEGER NOT NULL,
    tags VARCHAR(50) NOT NULL,
    is_ach_payment INTEGER NOT NULL,
    ach_payment_status VARCHAR(100),
    ach_gw_transaction_id INTEGER PRIMARY KEY AUTOINCREMENT,
    check_details VARCHAR(255) NOT NULL,
    branch_id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    branch_name VARCHAR(255) NOT NULL,
    location_id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    PRIMARY KEY (payment_id, vendor_id, currency_id, paid_through_account_id, ach_gw_transaction_id, branch_id, location_id)
);

-- Line Item Tables
--------------------------------------------------
-- Table: json_bills_line_items
CREATE TABLE IF NOT EXISTS json_bills_line_items (
    purchaseorder_id INTEGER PRIMARY KEY AUTOINCREMENT,
    purchaseorder_item_id INTEGER PRIMARY KEY AUTOINCREMENT,
    receive_id INTEGER PRIMARY KEY AUTOINCREMENT,
    line_item_id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    item_id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    image_document_id INTEGER PRIMARY KEY AUTOINCREMENT,
    sku TEXT,
    name VARCHAR(255) NOT NULL,
    account_id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    account_name VARCHAR(255) NOT NULL,
    description VARCHAR(255),
    bcy_rate REAL NOT NULL,
    rate REAL NOT NULL,
    sales_rate REAL NOT NULL,
    sales_margin TEXT,
    pricebook_id INTEGER PRIMARY KEY AUTOINCREMENT,
    header_id INTEGER PRIMARY KEY AUTOINCREMENT,
    header_name TEXT,
    tags VARCHAR(50) NOT NULL,
    quantity REAL NOT NULL,
    discount REAL NOT NULL,
    discounts VARCHAR(50) NOT NULL,
    discount_account_id INTEGER PRIMARY KEY AUTOINCREMENT,
    discount_account_name TEXT,
    markup_percent REAL NOT NULL,
    tax_id INTEGER PRIMARY KEY AUTOINCREMENT,
    tax_name TEXT,
    tax_type VARCHAR(100) NOT NULL,
    tax_percentage INTEGER NOT NULL,
    tds_tax_id INTEGER PRIMARY KEY AUTOINCREMENT,
    tds_tax_name VARCHAR(255),
    tds_tax_percentage REAL,
    tds_tax_amount DECIMAL(15,2) NOT NULL,
    tds_tax_type VARCHAR(100) NOT NULL,
    line_item_taxes VARCHAR(50) NOT NULL,
    line_item_tds VARCHAR(255) NOT NULL,
    item_total DECIMAL(15,2) NOT NULL,
    item_order INTEGER NOT NULL,
    unit TEXT,
    item_type VARCHAR(100) NOT NULL,
    image_name TEXT,
    image_type VARCHAR(100),
    is_billable INTEGER NOT NULL,
    is_landedcost DECIMAL(15,2) NOT NULL,
    customer_id INTEGER PRIMARY KEY AUTOINCREMENT,
    receipt_line_item_id INTEGER PRIMARY KEY AUTOINCREMENT,
    customer_name TEXT,
    project_id INTEGER PRIMARY KEY AUTOINCREMENT,
    project_name TEXT,
    invoice_id INTEGER PRIMARY KEY AUTOINCREMENT,
    invoice_number TEXT,
    item_custom_fields VARCHAR(50) NOT NULL,
    purchase_request_items VARCHAR(50) NOT NULL,
    item_matching_type VARCHAR(100),
    parent_id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    parent_type VARCHAR(100) NOT NULL,
    PRIMARY KEY (purchaseorder_id, purchaseorder_item_id, receive_id, line_item_id, item_id, image_document_id, account_id, pricebook_id, header_id, discount_account_id, tax_id, tds_tax_id, customer_id, receipt_line_item_id, project_id, invoice_id, parent_id)
);

-- Table: json_creditnotes_line_items
CREATE TABLE IF NOT EXISTS json_creditnotes_line_items (
    item_id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    line_item_id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    sku TEXT,
    account_id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    account_name VARCHAR(255) NOT NULL,
    name VARCHAR(255) NOT NULL,
    internal_name TEXT,
    description VARCHAR(255),
    item_order INTEGER NOT NULL,
    invoice_id INTEGER PRIMARY KEY AUTOINCREMENT,
    invoice_item_id INTEGER PRIMARY KEY AUTOINCREMENT,
    quantity REAL NOT NULL,
    pricing_scheme VARCHAR(50) NOT NULL,
    unit VARCHAR(50) NOT NULL,
    item_custom_fields VARCHAR(1000) NOT NULL,
    project_id INTEGER PRIMARY KEY AUTOINCREMENT,
    pricebook_id INTEGER PRIMARY KEY AUTOINCREMENT,
    discount_amount DECIMAL(15,2) NOT NULL,
    discount REAL NOT NULL,
    discounts VARCHAR(50) NOT NULL,
    discount_account_id INTEGER PRIMARY KEY AUTOINCREMENT,
    discount_account_name TEXT,
    asset_price DECIMAL(15,2) NOT NULL,
    asset_value REAL NOT NULL,
    bcy_rate REAL NOT NULL,
    rate REAL NOT NULL,
    sales_margin TEXT,
    tax_id INTEGER PRIMARY KEY AUTOINCREMENT,
    tax_name TEXT,
    tax_type VARCHAR(100) NOT NULL,
    tax_percentage INTEGER NOT NULL,
    tds_tax_id INTEGER PRIMARY KEY AUTOINCREMENT,
    tds_tax_name TEXT,
    tds_tax_percentage TEXT,
    tds_tax_amount DECIMAL(15,2) NOT NULL,
    line_item_taxes VARCHAR(50) NOT NULL,
    line_item_tds VARCHAR(50) NOT NULL,
    item_total DECIMAL(15,2) NOT NULL,
    item_type VARCHAR(100) NOT NULL,
    tags VARCHAR(50) NOT NULL,
    image_document_id INTEGER PRIMARY KEY AUTOINCREMENT,
    is_credit_only_item INTEGER NOT NULL,
    mapped_items VARCHAR(50) NOT NULL,
    parent_id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    parent_type VARCHAR(100) NOT NULL,
    PRIMARY KEY (item_id, line_item_id, account_id, invoice_id, invoice_item_id, project_id, pricebook_id, discount_account_id, tax_id, tds_tax_id, image_document_id, parent_id)
);

-- Table: json_invoices_line_items
CREATE TABLE IF NOT EXISTS json_invoices_line_items (
    line_item_id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    item_id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    sku VARCHAR(50),
    item_order INTEGER NOT NULL,
    name VARCHAR(255) NOT NULL,
    internal_name TEXT,
    description TEXT,
    discount_account_id INTEGER PRIMARY KEY AUTOINCREMENT,
    discount_account_name VARCHAR(255),
    unit VARCHAR(50) NOT NULL,
    quantity REAL NOT NULL,
    discount_amount DECIMAL(15,2) NOT NULL,
    discount REAL NOT NULL,
    discounts VARCHAR(255) NOT NULL,
    bcy_rate REAL NOT NULL,
    rate REAL NOT NULL,
    account_id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    account_name VARCHAR(255) NOT NULL,
    header_id INTEGER PRIMARY KEY AUTOINCREMENT,
    header_name TEXT,
    pricebook_id INTEGER PRIMARY KEY AUTOINCREMENT,
    tax_id INTEGER PRIMARY KEY AUTOINCREMENT,
    tax_name TEXT,
    tax_type VARCHAR(100) NOT NULL,
    tax_percentage INTEGER NOT NULL,
    item_total DECIMAL(15,2) NOT NULL,
    item_custom_fields VARCHAR(1000) NOT NULL,
    pricing_scheme VARCHAR(50),
    tags VARCHAR(50) NOT NULL,
    documents VARCHAR(50) NOT NULL,
    image_document_id INTEGER PRIMARY KEY AUTOINCREMENT,
    tds_tax_id INTEGER PRIMARY KEY AUTOINCREMENT,
    tds_tax_name TEXT,
    tds_tax_percentage TEXT,
    tds_tax_amount DECIMAL(15,2) NOT NULL,
    line_item_taxes VARCHAR(50) NOT NULL,
    line_item_tds VARCHAR(50) NOT NULL,
    bill_id INTEGER PRIMARY KEY AUTOINCREMENT,
    bill_item_id INTEGER PRIMARY KEY AUTOINCREMENT,
    project_id INTEGER PRIMARY KEY AUTOINCREMENT,
    time_entry_ids DATETIME NOT NULL,
    expense_id INTEGER PRIMARY KEY AUTOINCREMENT,
    item_type VARCHAR(100) NOT NULL,
    expense_receipt_name TEXT,
    sales_rate REAL NOT NULL,
    purchase_rate REAL NOT NULL,
    salesorder_item_id INTEGER PRIMARY KEY AUTOINCREMENT,
    cost_amount DECIMAL(15,2) NOT NULL,
    markup_percent INTEGER NOT NULL,
    mapped_items VARCHAR(50) NOT NULL,
    parent_id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    parent_type VARCHAR(100) NOT NULL,
    PRIMARY KEY (line_item_id, item_id, discount_account_id, account_id, header_id, pricebook_id, tax_id, image_document_id, tds_tax_id, bill_id, bill_item_id, project_id, expense_id, salesorder_item_id, parent_id)
);

-- Table: json_purchaseorders_line_items
CREATE TABLE IF NOT EXISTS json_purchaseorders_line_items (
    item_id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    line_item_id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    salesorder_item_id INTEGER PRIMARY KEY AUTOINCREMENT,
    image_document_id INTEGER PRIMARY KEY AUTOINCREMENT,
    sku VARCHAR(50),
    account_id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    account_name VARCHAR(255) NOT NULL,
    name VARCHAR(255) NOT NULL,
    description TEXT,
    item_order INTEGER NOT NULL,
    is_receivable INTEGER NOT NULL,
    bcy_rate REAL NOT NULL,
    pricebook_id INTEGER PRIMARY KEY AUTOINCREMENT,
    header_id INTEGER PRIMARY KEY AUTOINCREMENT,
    header_name TEXT,
    rate REAL NOT NULL,
    quantity REAL NOT NULL,
    discount REAL NOT NULL,
    discounts VARCHAR(50) NOT NULL,
    quantity_marked_as_received REAL NOT NULL,
    quantity_cancelled REAL NOT NULL,
    quantity_billed REAL NOT NULL,
    unit VARCHAR(50),
    item_total DECIMAL(15,2) NOT NULL,
    tax_id INTEGER PRIMARY KEY AUTOINCREMENT,
    tax_name TEXT,
    tax_type VARCHAR(100) NOT NULL,
    tax_percentage INTEGER NOT NULL,
    tds_tax_id INTEGER PRIMARY KEY AUTOINCREMENT,
    tds_tax_name TEXT,
    tds_tax_percentage TEXT,
    tds_tax_amount DECIMAL(15,2) NOT NULL,
    item_type VARCHAR(100) NOT NULL,
    line_item_taxes VARCHAR(50) NOT NULL,
    line_item_tds VARCHAR(50) NOT NULL,
    tags VARCHAR(50) NOT NULL,
    item_custom_fields VARCHAR(50) NOT NULL,
    project_id INTEGER PRIMARY KEY AUTOINCREMENT,
    image_name TEXT,
    image_type VARCHAR(100),
    purchase_request_items VARCHAR(50) NOT NULL,
    parent_id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    parent_type VARCHAR(100) NOT NULL,
    PRIMARY KEY (item_id, line_item_id, salesorder_item_id, image_document_id, account_id, pricebook_id, header_id, tax_id, tds_tax_id, project_id, parent_id)
);

-- Table: json_salesorders_line_items
CREATE TABLE IF NOT EXISTS json_salesorders_line_items (
    line_item_id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    variant_id INTEGER PRIMARY KEY AUTOINCREMENT,
    item_id INTEGER PRIMARY KEY AUTOINCREMENT,
    product_id INTEGER PRIMARY KEY AUTOINCREMENT,
    attribute_name1 TEXT,
    attribute_name2 TEXT,
    attribute_name3 TEXT,
    attribute_option_name1 TEXT,
    attribute_option_name2 TEXT,
    attribute_option_name3 TEXT,
    attribute_option_data1 TEXT,
    attribute_option_data2 TEXT,
    attribute_option_data3 TEXT,
    is_combo_product INTEGER NOT NULL,
    combo_type VARCHAR(100),
    sku VARCHAR(50),
    name VARCHAR(255),
    group_name VARCHAR(255),
    description TEXT,
    item_order INTEGER NOT NULL,
    bcy_rate REAL NOT NULL,
    rate REAL NOT NULL,
    sales_rate REAL,
    quantity REAL NOT NULL,
    quantity_manuallyfulfilled REAL NOT NULL,
    unit VARCHAR(50),
    pricebook_id INTEGER PRIMARY KEY AUTOINCREMENT,
    header_id INTEGER PRIMARY KEY AUTOINCREMENT,
    header_name TEXT,
    discount_amount DECIMAL(15,2) NOT NULL,
    discount REAL NOT NULL,
    discounts VARCHAR(50) NOT NULL,
    tax_id INTEGER PRIMARY KEY AUTOINCREMENT,
    tax_name TEXT,
    tax_type VARCHAR(100) NOT NULL,
    tax_percentage INTEGER NOT NULL,
    tds_tax_id INTEGER PRIMARY KEY AUTOINCREMENT,
    tds_tax_name TEXT,
    tds_tax_percentage TEXT,
    tds_tax_amount DECIMAL(15,2) NOT NULL,
    line_item_taxes VARCHAR(50) NOT NULL,
    line_item_tds VARCHAR(50) NOT NULL,
    item_total DECIMAL(15,2) NOT NULL,
    item_sub_total DECIMAL(15,2) NOT NULL,
    product_type VARCHAR(100) NOT NULL,
    line_item_type VARCHAR(100) NOT NULL,
    item_type VARCHAR(100),
    is_invoiced INTEGER NOT NULL,
    tags VARCHAR(50) NOT NULL,
    image_name TEXT,
    image_type VARCHAR(100),
    image_document_id INTEGER PRIMARY KEY AUTOINCREMENT,
    document_id INTEGER PRIMARY KEY AUTOINCREMENT,
    item_custom_fields VARCHAR(1000) NOT NULL,
    custom_field_hash VARCHAR(255) NOT NULL,
    quantity_invoiced REAL NOT NULL,
    quantity_backordered INTEGER NOT NULL,
    quantity_cancelled REAL NOT NULL,
    is_fulfillable INTEGER NOT NULL,
    project_id INTEGER PRIMARY KEY AUTOINCREMENT,
    mapped_items VARCHAR(50) NOT NULL,
    parent_id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    parent_type VARCHAR(100) NOT NULL,
    PRIMARY KEY (line_item_id, variant_id, item_id, product_id, pricebook_id, header_id, tax_id, tds_tax_id, image_document_id, document_id, project_id, parent_id)
);

-- Indexes
--------------------------------------------------
CREATE INDEX IF NOT EXISTS idx_json_invoices_status ON json_invoices(status);
CREATE INDEX IF NOT EXISTS idx_json_invoices_reference_number ON json_invoices(reference_number);
CREATE INDEX IF NOT EXISTS idx_json_invoices_date ON json_invoices(date);
CREATE INDEX IF NOT EXISTS idx_json_invoices_email ON json_invoices(email);
CREATE INDEX IF NOT EXISTS idx_json_invoices_phone ON json_invoices(phone);
CREATE INDEX IF NOT EXISTS idx_json_items_name ON json_items(name);
CREATE INDEX IF NOT EXISTS idx_json_items_status ON json_items(status);
CREATE INDEX IF NOT EXISTS idx_json_contacts_status ON json_contacts(status);
CREATE INDEX IF NOT EXISTS idx_json_contacts_email ON json_contacts(email);
CREATE INDEX IF NOT EXISTS idx_json_contacts_phone ON json_contacts(phone);
CREATE INDEX IF NOT EXISTS idx_json_bills_status ON json_bills(status);
CREATE INDEX IF NOT EXISTS idx_json_bills_reference_number ON json_bills(reference_number);
CREATE INDEX IF NOT EXISTS idx_json_bills_date ON json_bills(date);
CREATE INDEX IF NOT EXISTS idx_json_organizations_name ON json_organizations(name);
CREATE INDEX IF NOT EXISTS idx_json_organizations_email ON json_organizations(email);
CREATE INDEX IF NOT EXISTS idx_json_organizations_phone ON json_organizations(phone);
CREATE INDEX IF NOT EXISTS idx_json_organizations_is_scan_preference_enabled ON json_organizations(is_scan_preference_enabled);
CREATE INDEX IF NOT EXISTS idx_json_customer_payments_date ON json_customer_payments(date);
CREATE INDEX IF NOT EXISTS idx_json_customer_payments_reference_number ON json_customer_payments(reference_number);
CREATE INDEX IF NOT EXISTS idx_json_vendor_payments_status ON json_vendor_payments(status);
CREATE INDEX IF NOT EXISTS idx_json_vendor_payments_date ON json_vendor_payments(date);
CREATE INDEX IF NOT EXISTS idx_json_vendor_payments_reference_number ON json_vendor_payments(reference_number);
CREATE INDEX IF NOT EXISTS idx_json_vendor_payments_paid_through_account_name ON json_vendor_payments(paid_through_account_name);
CREATE INDEX IF NOT EXISTS idx_json_vendor_payments_is_paid_via_print_check ON json_vendor_payments(is_paid_via_print_check);
CREATE INDEX IF NOT EXISTS idx_json_sales_orders_email ON json_sales_orders(email);
CREATE INDEX IF NOT EXISTS idx_json_sales_orders_reference_number ON json_sales_orders(reference_number);
CREATE INDEX IF NOT EXISTS idx_json_sales_orders_date ON json_sales_orders(date);
CREATE INDEX IF NOT EXISTS idx_json_sales_orders_paid_status ON json_sales_orders(paid_status);
CREATE INDEX IF NOT EXISTS idx_json_sales_orders_status ON json_sales_orders(status);
CREATE INDEX IF NOT EXISTS idx_json_purchase_orders_status ON json_purchase_orders(status);
CREATE INDEX IF NOT EXISTS idx_json_purchase_orders_reference_number ON json_purchase_orders(reference_number);
CREATE INDEX IF NOT EXISTS idx_json_purchase_orders_date ON json_purchase_orders(date);
CREATE INDEX IF NOT EXISTS idx_json_purchase_orders_tax_override_preference ON json_purchase_orders(tax_override_preference);
CREATE INDEX IF NOT EXISTS idx_json_purchase_orders_tds_override_preference ON json_purchase_orders(tds_override_preference);
CREATE INDEX IF NOT EXISTS idx_json_credit_notes_status ON json_credit_notes(status);
CREATE INDEX IF NOT EXISTS idx_json_credit_notes_reference_number ON json_credit_notes(reference_number);
CREATE INDEX IF NOT EXISTS idx_json_credit_notes_date ON json_credit_notes(date);
CREATE INDEX IF NOT EXISTS idx_json_invoices_line_items_name ON json_invoices_line_items(name);
CREATE INDEX IF NOT EXISTS idx_json_invoices_line_items_time_entry_ids ON json_invoices_line_items(time_entry_ids);
CREATE INDEX IF NOT EXISTS idx_json_bills_line_items_name ON json_bills_line_items(name);
CREATE INDEX IF NOT EXISTS idx_json_salesorders_line_items_name ON json_salesorders_line_items(name);
CREATE INDEX IF NOT EXISTS idx_json_purchaseorders_line_items_name ON json_purchaseorders_line_items(name);
CREATE INDEX IF NOT EXISTS idx_json_creditnotes_line_items_name ON json_creditnotes_line_items(name);

-- Schema generation complete