"""
Canonical Schema and JSON-to-Database Mapping Definitions

This module contains the master CANONICAL_SCHEMA dictionary and JSON-to-database
mapping dictionaries for all 10 core Zoho Books entities. This serves as the
unchanging blueprint for the entire data pipeline, specifically for mapping
JSON fields from Zoho API responses to the canonical database schema.

Entities covered:
1. Invoices (with line items)
2. Items (standalone) 
3. Contacts (with contact persons)
4. Bills (with line items)
5. Organizations (standalone)
6. CustomerPayments (with invoice applications)
7. VendorPayments (with bill applications)
8. SalesOrders (with line items)
9. PurchaseOrders (with line items)
10. CreditNotes (with line items)

Author: Data Pipeline Team
Generated: Auto-generated from canonical schema development notebook
Version: 1.0.0
"""
# ============================================================================
# MAPPINGS UPDATE - 2025-07-05 16:42:43
# ============================================================================
# Updated for JSON-to-database mapping. All mapping dictionaries now handle
# JSON field names from Zoho API responses to canonical database fields.
# Original CSV version backup: mappings_backup_2025-07-05_16-37-59.py
# ============================================================================



from typing import Dict, List, Optional, Any, Union

# ============================================================================
# CANONICAL_SCHEMA: Master Schema Definition for All 10 Entities
# ============================================================================

CANONICAL_SCHEMA = {
    'Invoices': {
        'header_table': 'Invoices',
        'primary_key': 'InvoiceID',
        'header_columns': {
            'InvoiceID': 'TEXT PRIMARY KEY',
            'InvoiceNumber': 'TEXT',
            'CustomerID': 'TEXT',
            'CustomerName': 'TEXT',
            'Date': 'TEXT',
            'DueDate': 'TEXT',
            'Status': 'TEXT',
            'SubTotal': 'REAL',
            'TaxTotal': 'REAL',
            'Total': 'REAL',
            'Balance': 'REAL',
            'CurrencyCode': 'TEXT',
            'ExchangeRate': 'REAL',
            'Notes': 'TEXT',
            'Terms': 'TEXT',
            'ReferenceNumber': 'TEXT',
            'SalesPersonName': 'TEXT',
            'BillingAddress': 'TEXT',
            'ShippingAddress': 'TEXT',
            'CreatedTime': 'TEXT',
            'LastModifiedTime': 'TEXT',
        },
        'has_line_items': True,
        'line_items_table': 'InvoiceLineItems',
        'line_item_pk': 'LineItemID',
        'foreign_key': 'InvoiceID',
        'line_items_columns': {
            'LineItemID': 'TEXT PRIMARY KEY',
            'InvoiceID': 'TEXT',
            'ItemID': 'TEXT',
            'ItemName': 'TEXT',
            'ItemDescription': 'TEXT',
            'SKU': 'TEXT',
            'Quantity': 'REAL',
            'Rate': 'REAL',
            'Unit': 'TEXT',
            'ItemTotal': 'REAL',
            'DiscountAmount': 'REAL',
            'TaxID': 'TEXT',
            'TaxName': 'TEXT',
            'TaxPercentage': 'REAL',
            'TaxType': 'TEXT',
            'ProjectID': 'TEXT',
            'ProjectName': 'TEXT',
        }
    },

    'Items': {
        'header_table': 'Items',
        'primary_key': 'ItemID',
        'header_columns': {
            'ItemID': 'TEXT PRIMARY KEY',
            'ItemName': 'TEXT',
            'SKU': 'TEXT',
            'ItemType': 'TEXT',
            'Category': 'TEXT',
            'Description': 'TEXT',
            'Rate': 'REAL',
            'Unit': 'TEXT',
            'PurchaseRate': 'REAL',
            'TaxID': 'TEXT',
            'TaxName': 'TEXT',
            'TaxPercentage': 'REAL',
            'PurchaseTaxID': 'TEXT',
            'PurchaseTaxName': 'TEXT',
            'PurchaseTaxPercentage': 'REAL',
            'InventoryAccountID': 'TEXT',
            'InventoryAccountName': 'TEXT',
            'AccountID': 'TEXT',
            'AccountName': 'TEXT',
            'PurchaseAccountID': 'TEXT',
            'PurchaseAccountName': 'TEXT',
            'IsActive': 'TEXT',
            'CreatedTime': 'TEXT',
            'LastModifiedTime': 'TEXT',
            # Additional columns from JSON field analysis - to match ITEMS_JSON_MAP
            'Account': 'TEXT',
            'Account Code': 'TEXT',
            'CF.Item Location': 'TEXT',
            'CF.M Box': 'TEXT',
            'CF.Manufacturer': 'TEXT',
            'CF.Product Category': 'TEXT',
            'CF.Product Sale Category': 'TEXT',
            'CF.S Box Qty': 'TEXT',
            'CF.SKU category': 'TEXT',
            'Inventory Account': 'TEXT',
            'Inventory Account Code': 'TEXT',
            'Inventory Valuation Method': 'TEXT',
            'Last Sync Time': 'TEXT',
            'Opening Stock': 'TEXT',
            'Opening Stock Value': 'TEXT',
            'Product Type': 'TEXT',
            'Purchase Account': 'TEXT',
            'Purchase Account Code': 'TEXT',
            'Purchase Description': 'TEXT',
            'Purchase Tax Type': 'TEXT',
            'Reference ID': 'TEXT',
            'Region': 'TEXT',
            'Reorder Point': 'TEXT',
            'Source': 'TEXT',
            'Stock On Hand': 'TEXT',
            'Tax Type': 'TEXT',
            'Usage unit': 'TEXT',
            'Vehicle': 'TEXT',
            'Vendor': 'TEXT',
        },
        'has_line_items': False,
        'line_items_table': None,
        'line_item_pk': None,
        'foreign_key': None,
        'line_items_columns': {
        }
    },

    'Contacts': {
        'header_table': 'Contacts',
        'primary_key': 'ContactID',
        'header_columns': {
            'ContactID': 'TEXT PRIMARY KEY',
            'ContactName': 'TEXT',
            'CompanyName': 'TEXT',
            'ContactType': 'TEXT',
            'Email': 'TEXT',
            'Phone': 'TEXT',
            'Mobile': 'TEXT',
            'Website': 'TEXT',
            'BillingAddress': 'TEXT',
            'ShippingAddress': 'TEXT',
            'CurrencyCode': 'TEXT',
            'PaymentTerms': 'TEXT',
            'CreditLimit': 'REAL',
            'VendorDisplayName': 'TEXT',
            'IsActive': 'TEXT',
            'Notes': 'TEXT',
            'CreatedTime': 'TEXT',
            'LastModifiedTime': 'TEXT',
        },
        'has_line_items': True,
        'line_items_table': 'ContactPersons',
        'line_item_pk': 'ContactPersonID',
        'foreign_key': 'ContactID',
        'line_items_columns': {
            'ContactPersonID': 'TEXT PRIMARY KEY',
            'ContactID': 'TEXT',
            'FirstName': 'TEXT',
            'LastName': 'TEXT',
            'Email': 'TEXT',
            'Phone': 'TEXT',
            'Mobile': 'TEXT',
            'Designation': 'TEXT',
            'Department': 'TEXT',
            'IsActive': 'TEXT',
        }
    },

    'Bills': {
        'header_table': 'Bills',
        'primary_key': 'BillID',
        'header_columns': {
            'BillID': 'TEXT PRIMARY KEY',
            'VendorID': 'TEXT',
            'VendorName': 'TEXT',
            'BillNumber': 'TEXT',
            'ReferenceNumber': 'TEXT',
            'Status': 'TEXT',
            'BillDate': 'TEXT',
            'DueDate': 'TEXT',
            'CurrencyCode': 'TEXT',
            'ExchangeRate': 'REAL',
            'SubTotal': 'REAL',
            'TaxTotal': 'REAL',
            'Total': 'REAL',
            'Balance': 'REAL',
            'Notes': 'TEXT',
            'Terms': 'TEXT',
            'CreatedTime': 'TEXT',
            'LastModifiedTime': 'TEXT',
        },
        'has_line_items': True,
        'line_items_table': 'BillLineItems',
        'line_item_pk': 'LineItemID',
        'foreign_key': 'BillID',
        'line_items_columns': {
            'LineItemID': 'TEXT PRIMARY KEY',
            'BillID': 'TEXT',
            'ItemID': 'TEXT',
            'ItemName': 'TEXT',
            'ItemDescription': 'TEXT',
            'SKU': 'TEXT',
            'Quantity': 'REAL',
            'Rate': 'REAL',
            'Unit': 'TEXT',
            'ItemTotal': 'REAL',
            'AccountID': 'TEXT',
            'AccountName': 'TEXT',
            'TaxID': 'TEXT',
            'TaxName': 'TEXT',
            'TaxPercentage': 'REAL',
            'TaxType': 'TEXT',
            'ProjectID': 'TEXT',
            'ProjectName': 'TEXT',
        }
    },

    'Organizations': {
        'header_table': 'Organizations',
        'primary_key': 'OrganizationID',
        'header_columns': {
            'OrganizationID': 'TEXT PRIMARY KEY',
            'OrganizationName': 'TEXT',
            'Email': 'TEXT',
            'Phone': 'TEXT',
            'Fax': 'TEXT',
            'Website': 'TEXT',
            'Address': 'TEXT',
            'City': 'TEXT',
            'State': 'TEXT',
            'Country': 'TEXT',
            'ZipCode': 'TEXT',
            'CurrencyCode': 'TEXT',
            'TimeZone': 'TEXT',
            'FiscalYearStart': 'TEXT',
            'TaxBasis': 'TEXT',
            'IsActive': 'TEXT',
            'CreatedTime': 'TEXT',
            'LastModifiedTime': 'TEXT',
        },
        'has_line_items': False,
        'line_items_table': None,
        'line_item_pk': None,
        'foreign_key': None,
        'line_items_columns': {
        }
    },

    'CustomerPayments': {
        'header_table': 'CustomerPayments',
        'primary_key': 'PaymentID',
        'header_columns': {
            'PaymentID': 'TEXT PRIMARY KEY',
            'CustomerID': 'TEXT',
            'CustomerName': 'TEXT',
            'PaymentNumber': 'TEXT',
            'Date': 'TEXT',
            'PaymentMode': 'TEXT',
            'ReferenceNumber': 'TEXT',
            'Amount': 'REAL',
            'BankCharges': 'REAL',
            'CurrencyCode': 'TEXT',
            'ExchangeRate': 'REAL',
            'Description': 'TEXT',
            'Notes': 'TEXT',
            'CreatedTime': 'TEXT',
            'LastModifiedTime': 'TEXT',
        },
        'has_line_items': True,
        'line_items_table': 'InvoiceApplications',
        'line_item_pk': 'ApplicationID',
        'foreign_key': 'PaymentID',
        'line_items_columns': {
            'ApplicationID': 'TEXT PRIMARY KEY',
            'PaymentID': 'TEXT',
            'InvoiceID': 'TEXT',
            'InvoiceNumber': 'TEXT',
            'AmountApplied': 'REAL',
            'TaxAmountWithheld': 'REAL',
        }
    },

    'VendorPayments': {
        'header_table': 'VendorPayments',
        'primary_key': 'PaymentID',
        'header_columns': {
            'PaymentID': 'TEXT PRIMARY KEY',
            'VendorID': 'TEXT',
            'VendorName': 'TEXT',
            'PaymentNumber': 'TEXT',
            'Date': 'TEXT',
            'PaymentMode': 'TEXT',
            'ReferenceNumber': 'TEXT',
            'Amount': 'REAL',
            'BankCharges': 'REAL',
            'CurrencyCode': 'TEXT',
            'ExchangeRate': 'REAL',
            'Description': 'TEXT',
            'Notes': 'TEXT',
            'CreatedTime': 'TEXT',
            'LastModifiedTime': 'TEXT',
        },
        'has_line_items': True,
        'line_items_table': 'BillApplications',
        'line_item_pk': 'ApplicationID',
        'foreign_key': 'PaymentID',
        'line_items_columns': {
            'ApplicationID': 'TEXT PRIMARY KEY',
            'PaymentID': 'TEXT',
            'BillID': 'TEXT',
            'BillNumber': 'TEXT',
            'AmountApplied': 'REAL',
            'TaxAmountWithheld': 'REAL',
        }
    },

    'SalesOrders': {
        'header_table': 'SalesOrders',
        'primary_key': 'SalesOrderID',
        'header_columns': {
            'SalesOrderID': 'TEXT PRIMARY KEY',
            'SalesOrderNumber': 'TEXT',
            'CustomerID': 'TEXT',
            'CustomerName': 'TEXT',
            'Date': 'TEXT',
            'ExpectedShipmentDate': 'TEXT',
            'Status': 'TEXT',
            'SubTotal': 'REAL',
            'TaxTotal': 'REAL',
            'Total': 'REAL',
            'CurrencyCode': 'TEXT',
            'ExchangeRate': 'REAL',
            'Notes': 'TEXT',
            'Terms': 'TEXT',
            'BillingAddress': 'TEXT',
            'ShippingAddress': 'TEXT',
            'CreatedTime': 'TEXT',
            'LastModifiedTime': 'TEXT',
        },
        'has_line_items': True,
        'line_items_table': 'SalesOrderLineItems',
        'line_item_pk': 'LineItemID',
        'foreign_key': 'SalesOrderID',
        'line_items_columns': {
            'LineItemID': 'TEXT PRIMARY KEY',
            'SalesOrderID': 'TEXT',
            'ItemID': 'TEXT',
            'ItemName': 'TEXT',
            'ItemDescription': 'TEXT',
            'SKU': 'TEXT',
            'Quantity': 'REAL',
            'QuantityShipped': 'REAL',
            'Rate': 'REAL',
            'Unit': 'TEXT',
            'ItemTotal': 'REAL',
            'TaxID': 'TEXT',
            'TaxName': 'TEXT',
            'TaxPercentage': 'REAL',
            'TaxType': 'TEXT',
        }
    },

    'PurchaseOrders': {
        'header_table': 'PurchaseOrders',
        'primary_key': 'PurchaseOrderID',
        'header_columns': {
            'PurchaseOrderID': 'TEXT PRIMARY KEY',
            'PurchaseOrderNumber': 'TEXT',
            'VendorID': 'TEXT',
            'VendorName': 'TEXT',
            'Date': 'TEXT',
            'ExpectedDeliveryDate': 'TEXT',
            'Status': 'TEXT',
            'SubTotal': 'REAL',
            'TaxTotal': 'REAL',
            'Total': 'REAL',
            'CurrencyCode': 'TEXT',
            'ExchangeRate': 'REAL',
            'Notes': 'TEXT',
            'Terms': 'TEXT',
            'BillingAddress': 'TEXT',
            'DeliveryAddress': 'TEXT',
            'CreatedTime': 'TEXT',
            'LastModifiedTime': 'TEXT',
        },
        'has_line_items': True,
        'line_items_table': 'PurchaseOrderLineItems',
        'line_item_pk': 'LineItemID',
        'foreign_key': 'PurchaseOrderID',
        'line_items_columns': {
            'LineItemID': 'TEXT PRIMARY KEY',
            'PurchaseOrderID': 'TEXT',
            'ItemID': 'TEXT',
            'ItemName': 'TEXT',
            'ItemDescription': 'TEXT',
            'SKU': 'TEXT',
            'Quantity': 'REAL',
            'QuantityReceived': 'REAL',
            'Rate': 'REAL',
            'Unit': 'TEXT',
            'ItemTotal': 'REAL',
            'TaxID': 'TEXT',
            'TaxName': 'TEXT',
            'TaxPercentage': 'REAL',
            'TaxType': 'TEXT',
        }
    },

    'CreditNotes': {
        'header_table': 'CreditNotes',
        'primary_key': 'CreditNoteID',
        'header_columns': {
            'CreditNoteID': 'TEXT PRIMARY KEY',
            'CreditNoteNumber': 'TEXT',
            'CustomerID': 'TEXT',
            'CustomerName': 'TEXT',
            'Date': 'TEXT',
            'Status': 'TEXT',
            'SubTotal': 'REAL',
            'TaxTotal': 'REAL',
            'Total': 'REAL',
            'Balance': 'REAL',
            'CurrencyCode': 'TEXT',
            'ExchangeRate': 'REAL',
            'ReferenceNumber': 'TEXT',
            'Reason': 'TEXT',
            'Notes': 'TEXT',
            'Terms': 'TEXT',
            'CreatedTime': 'TEXT',
            'LastModifiedTime': 'TEXT',
        },
        'has_line_items': True,
        'line_items_table': 'CreditNoteLineItems',
        'line_item_pk': 'LineItemID',
        'foreign_key': 'CreditNoteID',
        'line_items_columns': {
            'LineItemID': 'TEXT PRIMARY KEY',
            'CreditNoteID': 'TEXT',
            'ItemID': 'TEXT',
            'ItemName': 'TEXT',
            'ItemDescription': 'TEXT',
            'SKU': 'TEXT',
            'Quantity': 'REAL',
            'Rate': 'REAL',
            'Unit': 'TEXT',
            'ItemTotal': 'REAL',
            'TaxID': 'TEXT',
            'TaxName': 'TEXT',
            'TaxPercentage': 'REAL',
            'TaxType': 'TEXT',
        }
    },

}


# ============================================================================
# JSON-to-Database Mapping Dictionaries
# ============================================================================

# Invoices JSON-to-Database Mapping
INVOICE_JSON_MAP = {
    'Invoice ID': 'InvoiceID',
    'Invoice Number': 'InvoiceNumber',
    'Customer ID': 'CustomerID',
    'Customer Name': 'CustomerName',
    'Invoice Date': 'Date',
    'Due Date': 'DueDate',
    'Invoice Status': 'Status',
    'Sub Total': 'SubTotal',
    'Tax Total': 'TaxTotal',
    'Total': 'Total',
    'Balance': 'Balance',
    'Currency Code': 'CurrencyCode',
    'Exchange Rate': 'ExchangeRate',
    'Notes': 'Notes',
    'Terms & Conditions': 'Terms',
    'Reference Number': 'ReferenceNumber',
    'Sales Person Name': 'SalesPersonName',
    'Billing Address': 'BillingAddress',
    'Shipping Address': 'ShippingAddress',
    'Created Time': 'CreatedTime',
    'Last Modified Time': 'LastModifiedTime',
    'Line Item ID': 'LineItemID',
    'Item ID': 'ItemID',
    'Item Name': 'ItemName',
    'Item Description': 'ItemDescription',
    'SKU': 'SKU',
    'Quantity': 'Quantity',
    'Rate': 'Rate',
    'Unit': 'Unit',
    'Item Total': 'ItemTotal',
    'Discount Amount': 'DiscountAmount',
    'Tax ID': 'TaxID',
    'Tax Name': 'TaxName',
    'Tax Percentage': 'TaxPercentage',
    'Tax Type': 'TaxType',
    'Project ID': 'ProjectID',
    'Project Name': 'ProjectName',

    # Additional fields from JSON field analysis
    '2Checkout': '2Checkout',
    'Account': 'Account',
    'Account Code': 'Account Code',
    'Accounts Receivable': 'Accounts Receivable',
    'Adjustment': 'Adjustment',
    'Adjustment Account': 'Adjustment Account',
    'Adjustment Description': 'Adjustment Description',
    'Authorize.Net': 'Authorize.Net',
    'Billing Attention': 'Billing Attention',
    'Billing City': 'Billing City',
    'Billing Code': 'Billing Code',
    'Billing Country': 'Billing Country',
    'Billing Fax': 'Billing Fax',
    'Billing Phone': 'Billing Phone',
    'Billing State': 'Billing State',
    'Billing Street2': 'Billing Street2',
    'Braintree': 'Braintree',
    'Branch ID': 'Branch ID',
    'Branch Name': 'Branch Name',
    'Brand': 'Brand',
    'CF.Reason to Void': 'CF.Reason to Void',
    'Company ID': 'Company ID',
    'Custom Charges': 'Custom Charges',
    'Discount': 'Discount',
    'Discount Type': 'Discount Type',
    'Early Payment Discount Amount': 'Early Payment Discount Amount',
    'Early Payment Discount Due Days': 'Early Payment Discount Due Days',
    'Early Payment Discount Percentage': 'Early Payment Discount Percentage',
    'Entity Discount Amount': 'Entity Discount Amount',
    'Entity Discount Percent': 'Entity Discount Percent',
    'Estimate Number': 'Estimate Number',
    'Expected Payment Date': 'Expected Payment Date',
    'Expense Reference ID': 'Expense Reference ID',
    'Forte': 'Forte',
    'GoCardless': 'GoCardless',
    'Google Checkout': 'Google Checkout',
    'ICICI EazyPay': 'ICICI EazyPay',
    'Is Discount Before Tax': 'Is Discount Before Tax',
    'Is Inclusive Tax': 'Is Inclusive Tax',
    'Item Desc': 'Item Desc',
    'Item Price': 'Item Price',
    'Item Tax': 'Item Tax',
    'Item Tax %': 'Item Tax %',
    'Item Tax Amount': 'Item Tax Amount',
    'Item Tax Type': 'Item Tax Type',
    'Item.CF.SKU category': 'Item.CF.SKU category',
    'Kit Combo Item Name': 'Kit Combo Item Name',
    'Last Payment Date': 'Last Payment Date',
    'Partial Payments': 'Partial Payments',
    'PayPal': 'PayPal',
    'Payflow Pro': 'Payflow Pro',
    'Payment Terms': 'Payment Terms',
    'Payment Terms Label': 'Payment Terms Label',
    'Payments Pro': 'Payments Pro',
    'Paytm': 'Paytm',
    'PortCode': 'PortCode',
    'Primary Contact EmailID': 'Primary Contact EmailID',
    'Primary Contact Mobile': 'Primary Contact Mobile',
    'Primary Contact Phone': 'Primary Contact Phone',
    'Product ID': 'Product ID',
    'PurchaseOrder': 'PurchaseOrder',
    'Razorpay': 'Razorpay',
    'Recurrence Name': 'Recurrence Name',
    'Region': 'Region',
    'Round Off': 'Round Off',
    'Sales Order Number': 'Sales Order Number',
    'Sales person': 'Sales person',
    'Shipping Attention': 'Shipping Attention',
    'Shipping Bill Date': 'Shipping Bill Date',
    'Shipping Bill Total': 'Shipping Bill Total',
    'Shipping Bill#': 'Shipping Bill#',
    'Shipping Charge': 'Shipping Charge',
    'Shipping Charge Account': 'Shipping Charge Account',
    'Shipping Charge Tax %': 'Shipping Charge Tax %',
    'Shipping Charge Tax Amount': 'Shipping Charge Tax Amount',
    'Shipping Charge Tax ID': 'Shipping Charge Tax ID',
    'Shipping Charge Tax Name': 'Shipping Charge Tax Name',
    'Shipping Charge Tax Type': 'Shipping Charge Tax Type',
    'Shipping City': 'Shipping City',
    'Shipping Code': 'Shipping Code',
    'Shipping Country': 'Shipping Country',
    'Shipping Fax': 'Shipping Fax',
    'Shipping Phone Number': 'Shipping Phone Number',
    'Shipping State': 'Shipping State',
    'Shipping Street2': 'Shipping Street2',
    'Square': 'Square',
    'Stripe': 'Stripe',
    'SubTotal': 'SubTotal',
    'Subject': 'Subject',
    'TDS Amount': 'TDS Amount',
    'TDS Name': 'TDS Name',
    'TDS Percentage': 'TDS Percentage',
    'TDS Type': 'TDS Type',
    'Template Name': 'Template Name',
    'Usage unit': 'Usage unit',
    'Vehicle': 'Vehicle',
    'WePay': 'WePay',
    'WorldPay': 'WorldPay',
    'subscription_id': 'subscription_id',
    
    # High-frequency missing fields from JSON analysis
    'ach_payment_initiated': 'AchPaymentInitiated',
    'allow_partial_payments': 'AllowPartialPayments',
    'applied_credits': 'AppliedCredits',
    'auto_reminder_placed': 'AutoReminderPlaced',
    'can_send_in_mail': 'CanSendInMail',
    'client_viewed_time': 'ClientViewedTime',
    'color_code': 'ColorCode',
    'credits_applied': 'CreditsApplied',
    'current_sub_status': 'CurrentSubStatus',
    'current_sub_status_id': 'CurrentSubStatusId',
    'documents': 'Documents',
    'due_days': 'DueDays',
    'has_attachment': 'HasAttachment',
    'invoice_url': 'InvoiceUrl',
    'is_viewed_by_client': 'IsViewedByClient',
    'last_payment_date': 'LastPaymentDate',
    'payment_options': 'PaymentOptions',
    'payment_reminder_enabled': 'PaymentReminderEnabled',
    'price_precision': 'PricePrecision',
    'recurring_invoice_id': 'RecurringInvoiceId',
    'reminders_sent': 'RemindersSent',
    'salesperson_id': 'SalespersonId',
    'shipping_charge': 'ShippingCharge',
    'stop_reminder_until_payment_expected_date': 'StopReminderUntilPaymentExpectedDate',
    'template_id': 'TemplateId',
    'template_type': 'TemplateType',
    'write_off_amount': 'WriteOffAmount',
    'zcrm_potential_id': 'ZcrmPotentialId',
    'zcrm_potential_name': 'ZcrmPotentialName',
    
    # Nested address fields (snake_case variants)
    'billing_address.address': 'Billing Address.Address',
    'billing_address.attention': 'Billing Address.Attention',
    'billing_address.city': 'Billing Address.City',
    'billing_address.country': 'Billing Address.Country',
    'billing_address.fax': 'Billing Address.Fax',
    'billing_address.phone': 'Billing Address.Phone',
    'billing_address.state': 'Billing Address.State',
    'billing_address.street2': 'Billing Address.Street2',
    'billing_address.zipcode': 'Billing Address.Zipcode',
    'shipping_address.address': 'Shipping Address.Address',
    'shipping_address.attention': 'Shipping Address.Attention',
    'shipping_address.city': 'Shipping Address.City',
    'shipping_address.country': 'Shipping Address.Country',
    'shipping_address.fax': 'Shipping Address.Fax',
    'shipping_address.phone': 'Shipping Address.Phone',
    'shipping_address.state': 'Shipping Address.State',
    'shipping_address.street2': 'Shipping Address.Street2',
    'shipping_address.zipcode': 'Shipping Address.Zipcode',
    
    # Line items fields (snake_case variants)
    'line_items': 'LineItems',
    'line_items.account_id': 'Line Items.Account ID',
    'line_items.tax_id': 'Line Items.Tax ID',
    'line_items.item_id': 'Line Items.Item ID',
    'line_items.quantity': 'Line Items.Quantity',
    'line_items.rate': 'Line Items.Rate',
    'line_items.amount': 'Line Items.Amount',
    
    # Additional missing fields for near 100% coverage - Invoices
    'Branch Id': 'BranchId',
    'Company Name': 'CompanyName',
    'Country': 'Country',
    'Created By': 'CreatedBy',
    'Currency Id': 'CurrencyId',
    'Currency Symbol': 'CurrencySymbol',
    'Custom Field Hash': 'CustomFieldHash',
    'Customer Id': 'CustomerId',
    'Date': 'Date',
    'Email': 'Email',
    'Invoice Id': 'InvoiceId',
    'Invoice Url': 'InvoiceUrl',
    'Is Emailed': 'IsEmailed',
    'Last Reminder Sent Date': 'LastReminderSentDate',
    'Location Id': 'LocationId',
    'No Of Copies': 'NoOfCopies',
    'Payment Expected Date': 'PaymentExpectedDate',
    'Phone': 'Phone',
    'Printed': 'Printed',
    'Status': 'Status',
    'Submitted Date': 'SubmittedDate',
    'Tags': 'Tags',
    'Total': 'Total',
    'branch_id': 'branch_id',
    'company_name': 'company_name',
    'country': 'country',
    'created_by': 'created_by',
    'currency_id': 'currency_id',
    'currency_symbol': 'currency_symbol',
    'custom_field_hash': 'custom_field_hash',
    'customer_id': 'customer_id',
    'date': 'date',
    'email': 'email',
    'invoice_id': 'invoice_id',
    'is_emailed': 'is_emailed',
    'last_reminder_sent_date': 'last_reminder_sent_date',
    'location_id': 'location_id',
    'no_of_copies': 'no_of_copies',
    'payment_expected_date': 'payment_expected_date',
    'phone': 'phone',
    'printed': 'printed',
    'status': 'status',
    'submitted_date': 'submitted_date',
    'tags': 'tags',
    'total': 'total',
}

# Items JSON-to-Database Mapping
ITEMS_JSON_MAP = {
    'Item ID': 'ItemID',
    'Item Name': 'ItemName',
    'SKU': 'SKU',
    'Item Type': 'ItemType',
    'Category': 'Category',
    'Description': 'Description',
    'Rate': 'Rate',
    'Unit': 'Unit',
    'Purchase Rate': 'PurchaseRate',
    'Tax ID': 'TaxID',
    'Tax Name': 'TaxName',
    'Tax Percentage': 'TaxPercentage',
    'Purchase Tax ID': 'PurchaseTaxID',
    'Purchase Tax Name': 'PurchaseTaxName',
    'Purchase Tax Percentage': 'PurchaseTaxPercentage',
    'Inventory Account ID': 'InventoryAccountID',
    'Inventory Account Name': 'InventoryAccountName',
    'Account ID': 'AccountID',
    'Account Name': 'AccountName',
    'Purchase Account ID': 'PurchaseAccountID',
    'Purchase Account Name': 'PurchaseAccountName',
    'Status': 'IsActive',
    'Created Time': 'CreatedTime',
    'Last Modified Time': 'LastModifiedTime',

    # Additional fields from JSON field analysis
    'Account': 'Account',
    'Account Code': 'Account Code',
    'CF.Item Location': 'CF.Item Location',
    'CF.M Box': 'CF.M Box',
    'CF.Manufacturer': 'CF.Manufacturer',
    'CF.Product Category': 'CF.Product Category',
    'CF.Product Sale Category': 'CF.Product Sale Category',
    'CF.S Box Qty': 'CF.S Box Qty',
    'CF.SKU category': 'CF.SKU category',
    'Inventory Account': 'Inventory Account',
    'Inventory Account Code': 'Inventory Account Code',
    'Inventory Valuation Method': 'Inventory Valuation Method',
    'Last Sync Time': 'Last Sync Time',
    'Opening Stock': 'Opening Stock',
    'Opening Stock Value': 'Opening Stock Value',
    'Product Type': 'Product Type',
    'Purchase Account': 'Purchase Account',
    'Purchase Account Code': 'Purchase Account Code',
    'Purchase Description': 'Purchase Description',
    'Purchase Tax Type': 'Purchase Tax Type',
    'Reference ID': 'Reference ID',
    'Region': 'Region',
    'Reorder Point': 'Reorder Point',
    'Source': 'Source',
    'Stock On Hand': 'Stock On Hand',
    'Tax Type': 'Tax Type',
    'Usage unit': 'Usage unit',
    'Vehicle': 'Vehicle',
    'Vendor': 'Vendor',
    
    # High-frequency missing fields from JSON analysis
    'actual_available_stock': 'ActualAvailableStock',
    'available_stock': 'AvailableStock',
    'can_be_purchased': 'CanBePurchased',
    'can_be_sold': 'CanBeSold',
    'cf_item_location': 'CF.Item Location',
    'cf_item_location_unformatted': 'CF.Item Location Unformatted',
    'cf_m_box': 'CF.M Box',
    'cf_m_box_unformatted': 'CF.M Box Unformatted',
    'cf_manufacturer': 'CF.Manufacturer',
    'cf_manufacturer_unformatted': 'CF.Manufacturer Unformatted',
    'cf_product_category': 'CF.Product Category',
    'cf_product_category_unformatted': 'CF.Product Category Unformatted',
    'cf_product_sale_category': 'CF.Product Sale Category',
    'cf_product_sale_category_unformatted': 'CF.Product Sale Category Unformatted',
    'cf_s_box_qty': 'CF.S Box Qty',
    'cf_s_box_qty_unformatted': 'CF.S Box Qty Unformatted',
    'cf_sku_category': 'CF.SKU category',
    'cf_sku_category_unformatted': 'CF.SKU category Unformatted',
    'has_attachment': 'HasAttachment',
    'image_document_id': 'ImageDocumentId',
    'image_name': 'ImageName',
    'initial_stock': 'InitialStock',
    'initial_stock_rate': 'InitialStockRate',
    'is_combo_product': 'IsComboProduct',
    'is_linked_with_zoho_inventory': 'IsLinkedWithZohoInventory',
    'item_tax_preferences': 'ItemTaxPreferences',
    'package_details': 'PackageDetails',
    'preferred_vendor': 'PreferredVendor',
    'price_precision': 'PricePrecision',
    'show_in_storefront': 'ShowInStorefront',
    'tax_exemption_id': 'TaxExemptionId',
    'track_serial_number': 'TrackSerialNumber',
    'vendor_id': 'VendorId',
    'warehouse_details': 'WarehouseDetails',
    
    # Additional missing fields for near 100% coverage - Items
    'Account Id': 'AccountId',
    'Image Type': 'ImageType',
    'Is Linked With Zohocrm': 'IsLinkedWithZohocrm',
    'Item Id': 'ItemId',
    'Name': 'Name',
    'Purchase Account Id': 'PurchaseAccountId',
    'Reorder Level': 'ReorderLevel',
    'Sku': 'Sku',
    'Tags': 'Tags',
    'Tax Id': 'TaxId',
    'Track Inventory': 'TrackInventory',
    'Zcrm Product Id': 'ZcrmProductId',
    'image_type': 'image_type',
    'is_linked_with_zohocrm': 'is_linked_with_zohocrm',
    'name': 'name',
    'purchase_account_id': 'purchase_account_id',
    'reorder_level': 'reorder_level',
    'sku': 'sku',
    'tags': 'tags',
    'tax_id': 'tax_id',
    'track_inventory': 'track_inventory',
    'zcrm_product_id': 'zcrm_product_id',
}

# Contacts JSON-to-Database Mapping
CONTACTS_JSON_MAP = {
    'Contact ID': 'ContactID',
    'Contact Name': 'ContactName',
    'Company Name': 'CompanyName',
    'Contact Type': 'ContactType',
    'Email': 'Email',
    'Phone': 'Phone',
    'Mobile': 'Mobile',
    'Website': 'Website',
    'Billing Address': 'BillingAddress',
    'Shipping Address': 'ShippingAddress',
    'Currency Code': 'CurrencyCode',
    'Payment Terms': 'PaymentTerms',
    'Credit Limit': 'CreditLimit',
    'Vendor Display Name': 'VendorDisplayName',
    'Status': 'IsActive',
    'Notes': 'Notes',
    'Created Time': 'CreatedTime',
    'Last Modified Time': 'LastModifiedTime',
    'Contact Person ID': 'ContactPersonID',
    'First Name': 'FirstName',
    'Last Name': 'LastName',
    'Designation': 'Designation',
    'Department': 'Department',

    # Additional fields from JSON field analysis
    'Accounts Receivable': 'Accounts Receivable',
    'Bank Account Payment': 'Bank Account Payment',
    'Billing Attention': 'Billing Attention',
    'Billing City': 'Billing City',
    'Billing Code': 'Billing Code',
    'Billing Country': 'Billing Country',
    'Billing County': 'Billing County',
    'Billing Fax': 'Billing Fax',
    'Billing Phone': 'Billing Phone',
    'Billing State': 'Billing State',
    'Billing Street2': 'Billing Street2',
    'Branch ID': 'Branch ID',
    'Branch Name': 'Branch Name',
    'CF.Customer Category': 'CF.Customer Category',
    'CF.Customer Sales Executive': 'CF.Customer Sales Executive',
    'CF.Market Region': 'CF.Market Region',
    'CF.Special Scheme & Targets': 'CF.Special Scheme & Targets',
    'Company ID': 'Company ID',
    'Contact Address ID': 'Contact Address ID',
    'Customer Sub Type': 'Customer Sub Type',
    'Display Name': 'Display Name',
    'EmailID': 'EmailID',
    'Facebook': 'Facebook',
    'Last Sync Time': 'Last Sync Time',
    'MobilePhone': 'MobilePhone',
    'Opening Balance': 'Opening Balance',
    'Opening Balance Exchange Rate': 'Opening Balance Exchange Rate',
    'Owner Name': 'Owner Name',
    'Payment Terms Label': 'Payment Terms Label',
    'Portal Enabled': 'Portal Enabled',
    'Price List': 'Price List',
    'Primary Contact ID': 'Primary Contact ID',
    'Region': 'Region',
    'SIRET': 'SIRET',
    'Salutation': 'Salutation',
    'Shipping Attention': 'Shipping Attention',
    'Shipping City': 'Shipping City',
    'Shipping Code': 'Shipping Code',
    'Shipping Country': 'Shipping Country',
    'Shipping County': 'Shipping County',
    'Shipping Fax': 'Shipping Fax',
    'Shipping Phone': 'Shipping Phone',
    'Shipping State': 'Shipping State',
    'Shipping Street2': 'Shipping Street2',
    'Skype Identity': 'Skype Identity',
    'Source': 'Source',
    'Tax Name': 'Tax Name',
    'Tax Percentage': 'Tax Percentage',
    'Tax Type': 'Tax Type',
    'Taxable': 'Taxable',
    'Track TDS': 'Track TDS',
    'Twitter': 'Twitter',
    'Vehicle': 'Vehicle',
    
    # High-frequency missing fields from JSON analysis
    'account_id': 'AccountId',
    'account_name': 'AccountName',
    'ach_supported': 'AchSupported',
    'avatar_url': 'AvatarUrl',
    'can_edit_1099': 'CanEdit1099',
    'contact_salutation': 'ContactSalutation',
    'contact_sub_type': 'ContactSubType',
    'created_date': 'CreatedDate',
    'currency_id': 'CurrencyId',
    'custom_fields': 'CustomFields',
    'default_payment_terms': 'DefaultPaymentTerms',
    'default_payment_terms_label': 'DefaultPaymentTermsLabel',
    'documents': 'Documents',
    'enable_portal': 'EnablePortal',
    'first_name': 'FirstName',
    'has_transaction': 'HasTransaction',
    'is_crm_customer': 'IsCrmCustomer',
    'is_portal_enabled': 'IsPortalEnabled',
    'language_code': 'LanguageCode',
    'last_name': 'LastName',
    'payment_terms_label': 'PaymentTermsLabel',
    'place_of_contact': 'PlaceOfContact',
    'primary_contact_id': 'PrimaryContactId',
    'skype_identity': 'SkypeIdentity',
    'source': 'Source',
    'track_1099': 'Track1099',
    'unused_credits_receivable_amount': 'UnusedCreditsReceivableAmount',
    'unused_credits_payable_amount': 'UnusedCreditsPayableAmount',
    'vendor_type': 'VendorType',
    'zcrmaccount_id': 'ZcrmAccountId',
    'zcrm_account_name': 'ZcrmAccountName',
    
    # Nested address fields (snake_case variants)
    'billing_address.address': 'Billing Address.Address',
    'billing_address.attention': 'Billing Address.Attention',
    'billing_address.city': 'Billing Address.City',
    'billing_address.country': 'Billing Address.Country',
    'billing_address.fax': 'Billing Address.Fax',
    'billing_address.phone': 'Billing Address.Phone',
    'billing_address.state': 'Billing Address.State',
    'billing_address.street2': 'Billing Address.Street2',
    'billing_address.zipcode': 'Billing Address.Zipcode',
    'shipping_address.address': 'Shipping Address.Address',
    'shipping_address.attention': 'Shipping Address.Attention',
    'shipping_address.city': 'Shipping Address.City',
    'shipping_address.country': 'Shipping Address.Country',
    'shipping_address.fax': 'Shipping Address.Fax',
    'shipping_address.phone': 'Shipping Address.Phone',
    'shipping_address.state': 'Shipping Address.State',
    'shipping_address.street2': 'Shipping Address.Street2',
    'shipping_address.zipcode': 'Shipping Address.Zipcode',
    
    # Contact persons nested fields
    'contact_persons': 'ContactPersons',
    'contact_persons.contact_person_id': 'Contact Persons.Contact Person ID',
    'contact_persons.first_name': 'Contact Persons.First Name',
    'contact_persons.last_name': 'Contact Persons.Last Name',
    'contact_persons.email': 'Contact Persons.Email',
    'contact_persons.phone': 'Contact Persons.Phone',
    'contact_persons.mobile': 'Contact Persons.Mobile',
    'contact_persons.designation': 'Contact Persons.Designation',
    'contact_persons.department': 'Contact Persons.Department',
    'contact_persons.is_active': 'Contact Persons.Is Active',
    
    # High-frequency missing contact-specific fields for significantly higher coverage
    'Branch Id': 'BranchId',
    'Color Code': 'ColorCode',
    'Contact Id': 'ContactId',
    'Contact Type Formatted': 'ContactTypeFormatted',
    'Created Time Formatted': 'CreatedTimeFormatted',
    'Currency Id': 'CurrencyId',
    'Current Sub Status': 'CurrentSubStatus',
    'Current Sub Status Id': 'CurrentSubStatusId',
    'Custom Field Hash': 'CustomFieldHash',
    'Custom Fields List': 'CustomFieldsList',
    'Customer Credit Limit': 'CustomerCreditLimit',
    'Customer Id': 'CustomerId',
    'Date': 'Date',
    'Has Attachment': 'HasAttachment',
    'Location Id': 'LocationId',
    'Payment Terms': 'PaymentTerms',
    'Status': 'Status',
    'Tags': 'Tags',
    'Cf Customer Category': 'CfCustomerCategory',
    'Cf Customer Category Unformatted': 'CfCustomerCategoryUnformatted',
    'Cf Customer Owner': 'CfCustomerOwner',
    'Cf Customer Owner Unformatted': 'CfCustomerOwnerUnformatted',
    'Cf Market Region': 'CfMarketRegion',
    'Cf Market Region Unformatted': 'CfMarketRegionUnformatted',
    'Cf Region': 'CfRegion',
    'Cf Region Unformatted': 'CfRegionUnformatted',
    'Cf Special Scheme Targets': 'CfSpecialSchemeTargets',
    'Cf Special Scheme Targets Unformatted': 'CfSpecialSchemeTargetsUnformatted',
    'Amount': 'Amount',
    'Balance': 'Balance',
    'Bcy Total': 'BcyTotal',
    'Customer Name': 'CustomerName',
    'Delivery Date': 'DeliveryDate',
    'Delivery Method': 'DeliveryMethod',
    'Delivery Method Id': 'DeliveryMethodId',
    'Description': 'Description',
    'Discount': 'Discount',
    'Discount Amount': 'DiscountAmount',
    'Discount Type': 'DiscountType',
    'Due Date': 'DueDate',
    'Exchange Rate': 'ExchangeRate',
    'Invoice Id': 'InvoiceId',
    'Invoice Number': 'InvoiceNumber',
    'Is Inclusive Tax': 'IsInclusiveTax',
    'Item Id': 'ItemId',
    'Item Name': 'ItemName',
    'Last Modified Time': 'LastModifiedTime',
    'Notes': 'Notes',
    'Order Number': 'OrderNumber',
    'Payment Mode': 'PaymentMode',
    'Payment Refund': 'PaymentRefund',
    'Quantity': 'Quantity',
    'Rate': 'Rate',
    'Reference Number': 'ReferenceNumber',
    'Refund Mode': 'RefundMode',
    'Sales Order Number': 'SalesOrderNumber',
    'Salesorder Id': 'SalesorderId',
    'Sub Total': 'SubTotal',
    'Tax Amount': 'TaxAmount',
    'Tax Total': 'TaxTotal',
    'Total': 'Total',
    'Unit': 'Unit',
    'branch_id': 'branch_id',
    'color_code': 'color_code',
    'contact_id': 'contact_id',
    'currency_id': 'currency_id',
    'current_sub_status': 'current_sub_status',
    'current_sub_status_id': 'current_sub_status_id',
    'custom_field_hash': 'custom_field_hash',
    'custom_fields_list': 'custom_fields_list',
    'customer_id': 'customer_id',
    'date': 'date',
    'has_attachment': 'has_attachment',
    'location_id': 'location_id',
    'payment_terms': 'payment_terms',
    'status': 'status',
    'tags': 'tags',
}
# Bills JSON-to-Database Mapping
BILLS_JSON_MAP = {
    'Bill ID': 'BillID',
    'Vendor ID': 'VendorID',
    'Vendor Name': 'VendorName',
    'Bill Number': 'BillNumber',
    'Reference Number': 'ReferenceNumber',
    'Bill Status': 'Status',
    'Bill Date': 'BillDate',
    'Due Date': 'DueDate',
    'Currency Code': 'CurrencyCode',
    'Exchange Rate': 'ExchangeRate',
    'Sub Total': 'SubTotal',
    'Tax Total': 'TaxTotal',
    'Total': 'Total',
    'Balance': 'Balance',
    'Notes': 'Notes',
    'Terms & Conditions': 'Terms',
    'Created Time': 'CreatedTime',
    'Last Modified Time': 'LastModifiedTime',
    'Line Item ID': 'LineItemID',
    'Item ID': 'ItemID',
    'Item Name': 'ItemName',
    'Item Description': 'ItemDescription',
    'SKU': 'SKU',
    'Quantity': 'Quantity',
    'Rate': 'Rate',
    'Unit': 'Unit',
    'Item Total': 'ItemTotal',
    'Account ID': 'AccountID',
    'Account Name': 'AccountName',
    'Tax ID': 'TaxID',
    'Tax Name': 'TaxName',
    'Tax Percentage': 'TaxPercentage',
    'Tax Type': 'TaxType',
    'Project ID': 'ProjectID',
    'Project Name': 'ProjectName',

    # Additional fields from JSON field analysis
    'Account': 'Account',
    'Account Code': 'Account Code',
    'Accounts Payable': 'Accounts Payable',
    'Adjustment': 'Adjustment',
    'Adjustment Account': 'Adjustment Account',
    'Adjustment Description': 'Adjustment Description',
    'Approved By': 'Approved By',
    'Approved Date': 'Approved Date',
    'Bill Type': 'Bill Type',
    'Branch ID': 'Branch ID',
    'Branch Name': 'Branch Name',
    'CF.ChP Scheme Settlement Period': 'CF.ChP Scheme Settlement Period',
    'Created By': 'Created By',
    'Customer Name': 'Customer Name',
    'Description': 'Description',
    'Discount': 'Discount',
    'Discount Account': 'Discount Account',
    'Discount Account Code': 'Discount Account Code',
    'Discount Amount': 'Discount Amount',
    'Discount Type': 'Discount Type',
    'Entity Discount Amount': 'Entity Discount Amount',
    'Entity Discount Percent': 'Entity Discount Percent',
    'Is Billable': 'Is Billable',
    'Is Discount Before Tax': 'Is Discount Before Tax',
    'Is Inclusive Tax': 'Is Inclusive Tax',
    'Is Landed Cost': 'Is Landed Cost',
    'Payment Terms': 'Payment Terms',
    'Payment Terms Label': 'Payment Terms Label',
    'Product ID': 'Product ID',
    'Purchase Order Number': 'Purchase Order Number',
    'PurchaseOrder': 'PurchaseOrder',
    'Region': 'Region',
    'SubTotal': 'SubTotal',
    'Submitted By': 'Submitted By',
    'Submitted Date': 'Submitted Date',
    'TDS Amount': 'TDS Amount',
    'TDS Name': 'TDS Name',
    'TDS Percentage': 'TDS Percentage',
    'TDS Type': 'TDS Type',
    'Tax Amount': 'Tax Amount',
    'Usage unit': 'Usage unit',
    'Vehicle': 'Vehicle',
    'Vendor Notes': 'Vendor Notes',
    
    # High-frequency missing fields from JSON analysis
    'attachment_name': 'AttachmentName',
    'client_viewed_time': 'ClientViewedTime',
    'color_code': 'ColorCode',
    'current_sub_status': 'CurrentSubStatus',
    'current_sub_status_id': 'CurrentSubStatusId',
    'date': 'Date',
    'due_days': 'DueDays',
    'has_attachment': 'HasAttachment',
    'is_viewed_by_client': 'IsViewedByClient',
    'open_purchaseorders_count': 'OpenPurchaseOrdersCount',
    'price_precision': 'PricePrecision',
    'recurring_bill_id': 'RecurringBillId',
    'source': 'Source',
    'stop_reminder_until_payment_expected_date': 'StopReminderUntilPaymentExpectedDate',
    'template_id': 'TemplateId',
    'template_name': 'TemplateName',
    'template_type': 'TemplateType',
    'unused_retainer_payments': 'UnusedRetainerPayments',
    'vendor_credit_no': 'VendorCreditNo',
    'zcrm_potential_id': 'ZcrmPotentialId',
    'zcrm_potential_name': 'ZcrmPotentialName',
    'cf_chp_scheme_settlement_perio': 'CF.ChP Scheme Settlement Period',
    'cf_chp_scheme_settlement_perio_unformatted': 'CF.ChP Scheme Settlement Period Unformatted',
    'currency_id': 'CurrencyId',
    'line_items': 'LineItems',
    
    # Additional missing fields for near 100% coverage - Bills
    'Bill Id': 'BillId',
    'Branch Id': 'BranchId',
    'Currency Id': 'CurrencyId',
    'Date': 'Date',
    'Entity Type': 'EntityType',
    'Is Bill Reconciliation Violated': 'IsBillReconciliationViolated',
    'Is Opening Balance': 'IsOpeningBalance',
    'Is Tally Bill': 'IsTallyBill',
    'Is Uber Bill': 'IsUberBill',
    'Line Items': 'LineItems',
    'Line Items.account Id': 'LineItems.AccountId',
    'Line Items.account Name': 'LineItems.AccountName',
    'Line Items.amount': 'LineItems.Amount',
    'Line Items.item Description': 'LineItems.ItemDescription',
    'Line Items.item Name': 'LineItems.ItemName',
    'Line Items.line Item Id': 'LineItems.LineItemId',
    'Line Items.quantity': 'LineItems.Quantity',
    'Line Items.rate': 'LineItems.Rate',
    'Line Items.tax Id': 'LineItems.TaxId',
    'Line Items.tax Name': 'LineItems.TaxName',
    'Line Items.tax Percentage': 'LineItems.TaxPercentage',
    'Line Items.tax Total': 'LineItems.TaxTotal',
    'Location Id': 'LocationId',
    'Status': 'Status',
    'Tags': 'Tags',
    'Total': 'Total',
    'Vendor Id': 'VendorId',
    'Vendor Name': 'VendorName',
    'bill_id': 'bill_id',
    'branch_id': 'branch_id',
    'entity_type': 'entity_type',
    'is_bill_reconciliation_violated': 'is_bill_reconciliation_violated',
    'is_opening_balance': 'is_opening_balance',
    'is_tally_bill': 'is_tally_bill',
    'is_uber_bill': 'is_uber_bill',
    'location_id': 'location_id',
    'status': 'status',
    'tags': 'tags',
    'total': 'total',
    'vendor_id': 'vendor_id',
    'vendor_name': 'vendor_name',
}

# CustomerPayments JSON-to-Database Mapping
CUSTOMER_PAYMENTS_JSON_MAP = {
    'CustomerPayment ID': 'PaymentID',
    'CustomerID': 'CustomerID',
    'Customer Name': 'CustomerName',
    'Payment Number': 'PaymentNumber',
    'Date': 'Date',
    'Mode': 'PaymentMode',
    'Reference Number': 'ReferenceNumber',
    'Amount': 'Amount',
    'Bank Charges': 'BankCharges',
    'Currency Code': 'CurrencyCode',
    'Exchange Rate': 'ExchangeRate',
    'Description': 'Description',
    'Created Time': 'CreatedTime',
    'InvoicePayment ID': 'ApplicationID',
    'Invoice Number': 'InvoiceNumber',
    'Amount Applied to Invoice': 'AmountApplied',
    'Withholding Tax Amount': 'TaxAmountWithheld',
    'Branch ID': 'BranchID',
    'Branch Name': 'BranchName',
    'Deposit To': 'DepositTo',
    'Deposit To Account Code': 'DepositToAccountCode',
    'Early Payment Discount': 'EarlyPaymentDiscount',
    'Invoice Date': 'InvoiceDate',
    'Invoice Payment Applied Date': 'InvoicePaymentAppliedDate',
    'Payment Number Prefix': 'PaymentNumberPrefix',
    'Payment Number Suffix': 'PaymentNumberSuffix',
    'Payment Type': 'PaymentType',
    'Tax Account': 'TaxAccount',
    'Unused Amount': 'UnusedAmount'
}

# VendorPayments JSON-to-Database Mapping
VENDOR_PAYMENTS_JSON_MAP = {
    'VendorPayment ID': 'PaymentID',
    'Vendor Name': 'VendorName',
    'Payment Number': 'PaymentNumber',
    'Date': 'Date',
    'Mode': 'PaymentMode',
    'Reference Number': 'ReferenceNumber',
    'Amount': 'Amount',
    'Currency Code': 'CurrencyCode',
    'Exchange Rate': 'ExchangeRate',
    'Description': 'Description',
    'Branch ID': 'BranchID',
    'Branch Name': 'BranchName',
    'Payment Status': 'Status',
    'EmailID': 'EmailID',
    'Paid Through': 'PaidThrough',
    'Paid Through Account Code': 'PaidThroughAccountCode',
    'Tax Account': 'TaxAccount',
    'Bank Reference Number': 'BankReferenceNumber',
    'PIPayment ID': 'ApplicationID',
    'Bill Amount': 'BillAmount',
    'Bill Payment Applied Date': 'BillPaymentAppliedDate',
    'Bill Date': 'BillDate',
    'Bill Number': 'BillNumber',
    'Withholding Tax Amount': 'WithholdingTaxAmount',
    'Withholding Tax Amount (BCY)': 'WithholdingTaxAmountBCY',
    'Payment Number Prefix': 'PaymentNumberPrefix',
    'Payment Number Suffix': 'PaymentNumberSuffix',
    'Unused Amount': 'UnusedAmount'
}

# SalesOrders JSON-to-Database Mapping
SALES_ORDERS_JSON_MAP = {
    'Sales Order ID': 'SalesOrderID',
    'Sales Order Number': 'SalesOrderNumber',
    'Customer ID': 'CustomerID',
    'Customer Name': 'CustomerName',
    'Date': 'Date',
    'Expected Shipment Date': 'ExpectedShipmentDate',
    'Status': 'Status',
    'Sub Total': 'SubTotal',
    'Tax Total': 'TaxTotal',
    'Total': 'Total',
    'Currency Code': 'CurrencyCode',
    'Exchange Rate': 'ExchangeRate',
    'Notes': 'Notes',
    'Terms & Conditions': 'Terms',
    'Billing Address': 'BillingAddress',
    'Shipping Address': 'ShippingAddress',
    'Created Time': 'CreatedTime',
    'Last Modified Time': 'LastModifiedTime',
    'Line Item ID': 'LineItemID',
    'Item ID': 'ItemID',
    'Item Name': 'ItemName',
    'Item Description': 'ItemDescription',
    'SKU': 'SKU',
    'Quantity': 'Quantity',
    'Quantity Shipped': 'QuantityShipped',
    'Rate': 'Rate',
    'Unit': 'Unit',
    'Item Total': 'ItemTotal',
    'Tax ID': 'TaxID',
    'Tax Name': 'TaxName',
    'Tax Percentage': 'TaxPercentage',
    'Tax Type': 'TaxType',

    # Additional fields from JSON field analysis
    'Account': 'Account',
    'Account Code': 'Account Code',
    'Adjustment': 'Adjustment',
    'Adjustment Description': 'Adjustment Description',
    'Billing City': 'Billing City',
    'Billing Code': 'Billing Code',
    'Billing Country': 'Billing Country',
    'Billing Fax': 'Billing Fax',
    'Billing Phone': 'Billing Phone',
    'Billing State': 'Billing State',
    'Billing Street2': 'Billing Street2',
    'Branch ID': 'Branch ID',
    'Branch Name': 'Branch Name',
    'CF.Pending Items Delivery': 'CF.Pending Items Delivery',
    'CF.Region': 'CF.Region',
    'Custom Status': 'Custom Status',
    'Delivery Method': 'Delivery Method',
    'Discount': 'Discount',
    'Discount Amount': 'Discount Amount',
    'Discount Type': 'Discount Type',
    'Entity Discount Amount': 'Entity Discount Amount',
    'Entity Discount Percent': 'Entity Discount Percent',
    'Is Discount Before Tax': 'Is Discount Before Tax',
    'Is Inclusive Tax': 'Is Inclusive Tax',
    'Item Desc': 'Item Desc',
    'Item Price': 'Item Price',
    'Item Tax': 'Item Tax',
    'Item Tax %': 'Item Tax %',
    'Item Tax Amount': 'Item Tax Amount',
    'Item Tax Type': 'Item Tax Type',
    'Item.CF.SKU category': 'Item.CF.SKU category',
    'Kit Combo Item Name': 'Kit Combo Item Name',
    'Order Date': 'Order Date',
    'Payment Terms': 'Payment Terms',
    'Payment Terms Label': 'Payment Terms Label',
    'Product ID': 'Product ID',
    'Project ID': 'Project ID',
    'Project Name': 'Project Name',
    'QuantityCancelled': 'QuantityCancelled',
    'QuantityInvoiced': 'QuantityInvoiced',
    'QuantityOrdered': 'QuantityOrdered',
    'Reference#': 'Reference#',
    'Region': 'Region',
    'Sales person': 'Sales person',
    'SalesOrder ID': 'SalesOrderID',
    'SalesOrder Number': 'SalesOrder Number',
    'Shipping Charge': 'Shipping Charge',
    'Shipping Charge Tax %': 'Shipping Charge Tax %',
    'Shipping Charge Tax Amount': 'Shipping Charge Tax Amount',
    'Shipping Charge Tax ID': 'Shipping Charge Tax ID',
    'Shipping Charge Tax Name': 'Shipping Charge Tax Name',
    'Shipping Charge Tax Type': 'Shipping Charge Tax Type',
    'Shipping City': 'Shipping City',
    'Shipping Code': 'Shipping Code',
    'Shipping Country': 'Shipping Country',
    'Shipping Fax': 'Shipping Fax',
    'Shipping Phone': 'Shipping Phone',
    'Shipping State': 'Shipping State',
    'Shipping Street2': 'Shipping Street2',
    'Source': 'Source',
    'SubTotal': 'SubTotal',
    'TDS Amount': 'TDS Amount',
    'TDS Name': 'TDS Name',
    'TDS Percentage': 'TDS Percentage',
    'TDS Type': 'TDS Type',
    'Template Name': 'Template Name',
    'Usage unit': 'Usage unit',
    'Vehicle': 'Vehicle',
}

# PurchaseOrders JSON-to-Database Mapping
PURCHASE_ORDERS_JSON_MAP = {
    'Purchase Order ID': 'PurchaseOrderID',
    'Purchase Order Number': 'PurchaseOrderNumber',
    'Vendor ID': 'VendorID',
    'Vendor Name': 'VendorName',
    'Date': 'Date',
    'Expected Delivery Date': 'ExpectedDeliveryDate',
    # Removed conflicting 'Status': 'Status' - use 'Purchase Order Status' below
    'Sub Total': 'SubTotal',
    'Tax Total': 'TaxTotal',
    'Total': 'Total',
    'Currency Code': 'CurrencyCode',
    'Exchange Rate': 'ExchangeRate',
    'Notes': 'Notes',
    'Terms & Conditions': 'Terms',
    'Billing Address': 'BillingAddress',
    'Delivery Address': 'DeliveryAddress',
    'Created Time': 'CreatedTime',
    'Last Modified Time': 'LastModifiedTime',
    'Line Item ID': 'LineItemID',
    'Item ID': 'ItemID',
    'Item Name': 'ItemName',
    'Item Description': 'ItemDescription',
    'SKU': 'SKU',
    'Quantity': 'Quantity',
    'Quantity Received': 'QuantityReceived',
    'Rate': 'Rate',
    'Unit': 'TEXT',
    'Item Total': 'ItemTotal',
    'Tax ID': 'TEXT',
    'Tax Name': 'TEXT',
    'Tax Percentage': 'REAL',
    'Tax Type': 'TEXT',

    # Additional fields from JSON field analysis
    'Account': 'Account',
    'Account Code': 'Account Code',
    'Address': 'Address',
    'Adjustment': 'Adjustment',
    'Adjustment Description': 'Adjustment Description',
    'Approved By': 'Approved By',
    'Approved Date': 'Approved Date',
    'Attention': 'Attention',
    'Branch ID': 'Branch ID',
    'Branch Name': 'Branch Name',
    'City': 'City',
    'Code': 'Code',
    'Country': 'Country',
    'Deliver To Customer': 'Deliver To Customer',
    'Delivery Date': 'Delivery Date',
    'Delivery Instructions': 'Delivery Instructions',
    'Discount': 'Discount',
    'Discount Account': 'Discount Account',
    'Discount Account Code': 'Discount Account Code',
    'Discount Amount': 'Discount Amount',
    'Discount Type': 'Discount Type',
    'Entity Discount Amount': 'Entity Discount Amount',
    'Entity Discount Percent': 'Entity Discount Percent',
    'Expected Arrival Date': 'Expected Arrival Date',
    'Is Discount Before Tax': 'Is Discount Before Tax',
    'Is Inclusive Tax': 'Is Inclusive Tax',
    'Item Desc': 'Item Desc',
    'Item Price': 'Item Price',
    'Item Tax': 'Item Tax',
    'Item Tax %': 'Item Tax %',
    'Item Tax Amount': 'Item Tax Amount',
    'Item Tax Type': 'Item Tax Type',
    'Payment Terms': 'Payment Terms',
    'Payment Terms Label': 'Payment Terms Label',
    'Phone': 'Phone',
    'Product ID': 'Product ID',
    'Project ID': 'Project ID',
    'Project Name': 'Project Name',
    'Purchase Order Date': 'Purchase Order Date',
    'Purchase Order Status': 'Status',  # Fixed: Map to correct DB column
    'QuantityBilled': 'QuantityBilled',
    'QuantityCancelled': 'QuantityCancelled',
    'QuantityOrdered': 'QuantityOrdered',
    'QuantityReceived': 'QuantityReceived',
    'Recipient Address': 'Recipient Address',
    'Recipient City': 'Recipient City',
    'Recipient Country': 'Recipient Country',
    'Recipient Phone': 'Recipient Phone',
    'Recipient Postal Code': 'Recipient Postal Code',
    'Recipient State': 'Recipient State',
    'Reference No': 'Reference No',
    'Reference#': 'Reference#',
    'Region': 'Region',
    'Shipment preference': 'Shipment preference',
    'State': 'State',
    'Submitted By': 'Submitted By',
    'Submitted Date': 'Submitted Date',
    'TDS Amount': 'TDS Amount',
    'TDS Name': 'TDS Name',
    'TDS Percentage': 'TDS Percentage',
    'TDS Type': 'TDS Type',
    'Template Name': 'Template Name',
    'Usage unit': 'Usage unit',
    'Vehicle': 'Vehicle',
}

# CreditNotes JSON-to-Database Mapping
CREDIT_NOTES_JSON_MAP = {
    'CreditNotes ID': 'CreditNoteID',  # Fixed: Use actual CSV column name
    'Credit Note Number': 'CreditNoteNumber',
    'Customer ID': 'CustomerID',
    'Customer Name': 'CustomerName',
    'Date': 'Date',
    # Removed conflicting 'Status': 'Status' - use 'Credit Note Status' below
    'Sub Total': 'SubTotal',
    'Tax Total': 'TaxTotal',
    'Total': 'Total',
    'Balance': 'Balance',
    'Currency Code': 'CurrencyCode',
    'Exchange Rate': 'ExchangeRate',
    'Reference Number': 'ReferenceNumber',
    'Reason': 'Reason',
    'Notes': 'Notes',
    'Terms & Conditions': 'Terms',
    'Created Time': 'CreatedTime',
    'Last Modified Time': 'LastModifiedTime',
    'Line Item ID': 'LineItemID',
    'Item ID': 'ItemID',
    'Item Name': 'ItemName',
    'Item Description': 'ItemDescription',
    'SKU': 'SKU',
    'Quantity': 'Quantity',
    'Rate': 'Rate',
    'Unit': 'Unit',
    'Item Total': 'ItemTotal',
    'Tax ID': 'TaxID',
    'Tax Name': 'TaxName',
    'Tax Percentage': 'TaxPercentage',
    'Tax Type': 'TaxType',

    # Additional fields from JSON field analysis
    'Account': 'Account',
    'Account Code': 'Account Code',
    'Accounts Receivable': 'Accounts Receivable',
    'Adjustment': 'Adjustment',
    'Adjustment Account': 'Adjustment Account',
    'Adjustment Description': 'Adjustment Description',
    'Applied Invoice Number': 'Applied Invoice Number',
    'Billing Address': 'Billing Address',
    'Billing Attention': 'Billing Attention',
    'Billing City': 'Billing City',
    'Billing Code': 'Billing Code',
    'Billing Country': 'Billing Country',
    'Billing Fax': 'Billing Fax',
    'Billing Phone': 'Billing Phone',
    'Billing State': 'Billing State',
    'Billing Street 2': 'Billing Street 2',
    'Branch ID': 'Branch ID',
    'Branch Name': 'Branch Name',
    'CF.Dispatch Incomplete but Scheme Passed': 'CF.Dispatch Incomplete but Scheme Passed',
    'CF.Modified': 'CF.Modified',
    'CF.Region': 'CF.Region',
    'CF.Scheme Settlement Period': 'CF.Scheme Settlement Period',
    'CF.Scheme Type': 'CF.Scheme Type',
    'Credit Note Date': 'Credit Note Date',
    'Credit Note Status': 'Status',  # Fixed: Map to correct DB column
    'Discount': 'Discount',
    'Discount Amount': 'Discount Amount',
    'Discount Type': 'Discount Type',
    'Entity Discount Amount': 'Entity Discount Amount',
    'Entity Discount Percent': 'Entity Discount Percent',
    'Is Discount Before Tax': 'Is Discount Before Tax',
    'Is Inclusive Tax': 'Is Inclusive Tax',
    'Item Desc': 'Item Desc',
    'Item Price': 'Item Price',
    'Item Tax': 'Item Tax',
    'Item Tax %': 'Item Tax %',
    'Item Tax Amount': 'Item Tax Amount',
    'Item Tax Type': 'Item Tax Type',
    'Item.CF.SKU category': 'Item.CF.SKU category',
    'Kit Combo Item Name': 'Kit Combo Item Name',
    'Product ID': 'Product ID',
    'Project ID': 'Project ID',
    'Project Name': 'Project Name',
    'Reference#': 'Reference#',
    'Region': 'Region',
    'Round Off': 'Round Off',
    'Sales person': 'Sales person',
    'Shipping Address': 'Shipping Address',
    'Shipping Attention': 'Shipping Attention',
    'Shipping Charge': 'Shipping Charge',
    'Shipping Charge Account': 'Shipping Charge Account',
    'Shipping Charge Tax %': 'Shipping Charge Tax %',
    'Shipping Charge Tax Amount': 'Shipping Charge Tax Amount',
    'Shipping Charge Tax ID': 'Shipping Charge Tax ID',
    'Shipping Charge Tax Name': 'Shipping Charge Tax Name',
    'Shipping Charge Tax Type': 'Shipping Charge Tax Type',
    'Shipping City': 'Shipping City',
    'Shipping Code': 'Shipping Code',
    'Shipping Country': 'Shipping Country',
    'Shipping Fax': 'Shipping Fax',
    'Shipping Phone': 'Shipping Phone',
    'Shipping State': 'Shipping State',
    'Shipping Street 2': 'Shipping Street 2',
    'SubTotal': 'SubTotal',
    'Subject': 'Subject',
    'TDS Amount': 'TDS Amount',
    'TDS Name': 'TDS Name',
    'TDS Percentage': 'TDS Percentage',
    'TDS Type': 'TDS Type',
    'Tax1 ID': 'Tax1 ID',
    'Template Name': 'Template Name',
    'Usage unit': 'Usage unit',
    'Vehicle': 'Vehicle',
}


# ============================================================================
# Helper Functions
# ============================================================================

def get_entity_schema(entity_name: str) -> Optional[Dict[str, Any]]:
    """
    Get the canonical schema for a specific entity.

    Args:
        entity_name: Name of the entity (e.g., 'Invoices', 'Bills')

    Returns:
        Dictionary containing the entity schema or None if not found
    """
    return CANONICAL_SCHEMA.get(entity_name)

def get_entity_json_mapping(entity_name: str) -> Optional[Dict[str, str]]:
    """
    Get the JSON-to-database mapping for a specific entity.

    Args:
        entity_name: Name of the entity (e.g., 'Invoices', 'Bills')

    Returns:
        Dictionary containing JSON field to canonical database column mappings
    """
    mapping_map = {
        'Invoices': INVOICE_JSON_MAP,
        'Items': ITEMS_JSON_MAP,
        'Contacts': CONTACTS_JSON_MAP,
        'Bills': BILLS_JSON_MAP,
        'CustomerPayments': CUSTOMER_PAYMENTS_JSON_MAP,
        'VendorPayments': VENDOR_PAYMENTS_JSON_MAP,
        'SalesOrders': SALES_ORDERS_JSON_MAP,
        'PurchaseOrders': PURCHASE_ORDERS_JSON_MAP,
        'CreditNotes': CREDIT_NOTES_JSON_MAP
    }
    return mapping_map.get(entity_name)

def get_all_entities() -> List[str]:
    """
    Get a list of all supported entity names.

    Returns:
        List of entity names
    """
    return list(CANONICAL_SCHEMA.keys())

def get_entities_with_line_items() -> List[str]:
    """
    Get a list of entities that have line items.

    Returns:
        List of entity names that have line items
    """
    return [
        entity_name for entity_name, config in CANONICAL_SCHEMA.items()
        if config['has_line_items']
    ]

def get_header_columns(entity_name: str) -> List[str]:
    """
    Get the header columns for a specific entity.

    Args:
        entity_name: Name of the entity

    Returns:
        List of header column names
    """
    schema = get_entity_schema(entity_name)
    return list(schema['header_columns'].keys()) if schema else []

def get_line_item_columns(entity_name: str) -> List[str]:
    """
    Get the line item columns for a specific entity.

    Args:
        entity_name: Name of the entity

    Returns:
        List of line item column names (empty if no line items)
    """
    schema = get_entity_schema(entity_name)
    if not schema:
        return []
    
    # Check if entity actually has line items before accessing line_items_columns
    if not schema.get('has_line_items', False):
        return []
    
    return list(schema.get('line_items_columns', {}).keys())

def validate_mapping_coverage(entity_name: str, json_fields: List[str]) -> Dict[str, List[str]]:
    """
    Validate the mapping coverage for an entity's JSON fields.

    Args:
        entity_name: Name of the entity
        json_fields: List of JSON field names

    Returns:
        Dictionary with 'mapped' and 'unmapped' lists
    """
    mapping = get_entity_json_mapping(entity_name)
    if not mapping:
        return {'mapped': [], 'unmapped': json_fields}

    mapped_columns = [col for col in json_fields if col in mapping]
    unmapped_columns = [col for col in json_fields if col not in mapping]

    return {
        'mapped': mapped_columns,
        'unmapped': unmapped_columns
    }

# ============================================================================
# Schema Statistics
# ============================================================================

def get_schema_statistics() -> Dict[str, Any]:
    """
    Get statistics about the canonical schema.

    Returns:
        Dictionary containing schema statistics
    """
    total_entities = len(CANONICAL_SCHEMA)
    entities_with_line_items = len(get_entities_with_line_items())
    entities_standalone = total_entities - entities_with_line_items

    total_header_columns = sum(
        len(config['header_columns']) for config in CANONICAL_SCHEMA.values()
    )
    total_line_item_columns = sum(
        len(config['line_items_columns']) for config in CANONICAL_SCHEMA.values()
    )

    return {
        'total_entities': total_entities,
        'entities_with_line_items': entities_with_line_items,
        'entities_standalone': entities_standalone,
        'total_header_columns': total_header_columns,
        'total_line_item_columns': total_line_item_columns,
        'total_columns': total_header_columns + total_line_item_columns
    }

# Module constants
__version__ = "1.0.0"
__all__ = [
    'CANONICAL_SCHEMA',
    'INVOICE_JSON_MAP',
    'ITEMS_JSON_MAP', 
    'CONTACTS_JSON_MAP',
    'BILLS_JSON_MAP',
    'CUSTOMER_PAYMENTS_JSON_MAP',
    'VENDOR_PAYMENTS_JSON_MAP',
    'SALES_ORDERS_JSON_MAP',
    'PURCHASE_ORDERS_JSON_MAP',
    'CREDIT_NOTES_JSON_MAP',
    'get_entity_schema',
    'get_entity_json_mapping',
    'get_all_entities',
    'get_entities_with_line_items',
    'get_header_columns',
    'get_line_item_columns',
    'validate_mapping_coverage',
    'get_schema_statistics'
]
